In [1]:
import pandas as pd

filepath = '/work/pipeline/3.5.Wide_exploded_genre.csv'
df = pd.read_csv(filepath)
df.head()

/tmp/ipykernel_651/2000162343.py:4: DtypeWarning: Columns (45,49,58,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filepath)

,tmdb_id,film_title,film_adult,film_runtime_min,film_genres,film_rating,film_vote_count,film_mpaa_rating,film_original_title,film_language_name,...,film_is_history,film_is_horror,film_is_music,film_is_mystery,film_is_romance,film_is_science_fiction,film_is_tv_movie,film_is_thriller,film_is_war,film_is_western
0,1027160,Alone in the Dark,False,90,"Horror, Thriller",4.769,13,NR,Alone in the Dark,English,...,False,True,False,False,False,False,False,True,False,False
1,1027160,Alone in the Dark,False,90,"Horror, Thriller",4.769,13,NR,Alone in the Dark,English,...,False,True,False,False,False,False,False,True,False,False
2,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,False,False,False,False,False,False,False,False,False,False
3,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,False,False,False,False,False,False,False,False,False,False
4,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,False,False,False,False,False,False,False,False,False,False

In [2]:
# Handle missing values to avoid errors during string split
df['film_genres'] = df['film_genres'].fillna('')

In [3]:
# Extract all unique genres from the entire dataset
unique_genres = set()
for entry in df['film_genres']:
    if entry:
        # Split by comma and strip whitespace from each genre
        genres = [g.strip() for g in entry.split(',')]
        unique_genres.update(genres)

In [4]:
# Sort them alphabetically for consistent column ordering
sorted_genres = sorted(list(unique_genres))
print(f"Detected Genres: {sorted_genres}")

Detected Genres: ['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']

In [5]:
# Create a binary column for each unique genre found
for genre in sorted_genres:
    # Format the column name (e.g., 'Science Fiction' becomes 'film_is_science_fiction')
    col_name = f"film_is_{genre.lower().replace(' ', '_')}"
    
    # Check if the genre string exists within the comma-separated list for each row
    df[col_name] = df['film_genres'].apply(
        lambda x: genre in [g.strip() for g in x.split(',')] if x else False
    )

In [6]:
df.head()

,tmdb_id,film_title,film_adult,film_runtime_min,film_genres,film_rating,film_vote_count,film_mpaa_rating,film_original_title,film_language_name,...,film_is_history,film_is_horror,film_is_music,film_is_mystery,film_is_romance,film_is_science_fiction,film_is_tv_movie,film_is_thriller,film_is_war,film_is_western
0,1027160,Alone in the Dark,False,90,"Horror, Thriller",4.769,13,NR,Alone in the Dark,English,...,False,True,False,False,False,False,False,True,False,False
1,1027160,Alone in the Dark,False,90,"Horror, Thriller",4.769,13,NR,Alone in the Dark,English,...,False,True,False,False,False,False,False,True,False,False
2,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,False,False,False,False,False,False,False,False,False,False
3,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,False,False,False,False,False,False,False,False,False,False
4,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,False,False,False,False,False,False,False,False,False,False

In [7]:
# Save the result to a new CSV file
output_file = '/work/pipeline/3.5.Wide_exploded_genre.csv'
df.to_csv(output_file, index=False)

print(f"Transformation complete. Saved to {output_file}")

Transformation complete. Saved to /work/pipeline/3.5.Wide_exploded_genre.csv

Below is really the same code, I modularized it so we can run this for albums

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=b124131d-2024-4253-bb46-8043aed4b78f' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>