In [1]:
# Standard library imports
import json
import os
import random
import time

# Third-party imports
import pandas as pd
import requests
from tqdm.auto import tqdm

/root/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
filepath = '/work/pipeline/4.3.Wide_spotify_ids.csv'
df_wide = pd.read_csv(filepath)
df_wide.head()

/tmp/ipykernel_4622/3643163095.py:2: DtypeWarning: Columns (45,49,58,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_wide = pd.read_csv(filepath)

,tmdb_id,film_title,film_adult,film_runtime_min,film_genres,film_rating,film_vote_count,film_mpaa_rating,film_original_title,film_language_name,...,film_is_tv_movie,film_is_thriller,film_is_war,film_is_western,vote_count_above_500,composer_primary_clean,track_title_cleaned,spotify_track_id,spotify_url,spotify_popularity
0,1027160,Alone in the Dark,False,90,"Horror, Thriller",4.769,13,NR,Alone in the Dark,English,...,False,True,False,False,False,Christopher French,Alone in the Dark Theme,NaN,NaN,NaN
1,1027160,Alone in the Dark,False,90,"Horror, Thriller",4.769,13,NR,Alone in the Dark,English,...,False,True,False,False,False,Christopher French,[data track],NaN,NaN,NaN
2,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,False,False,False,False,False,Tim Dewit,Gloc,7kVnKJS0UVB8ZtHC4czKBv,https://open.spotify.com/track/7kVnKJS0UVB8ZtH...,2.0
3,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,False,False,False,False,False,Tim Dewit,Move It Up,21h0xKdO8E7EY0H90fApYB,https://open.spotify.com/track/21h0xKdO8E7EY0H...,1.0
4,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,False,False,False,False,False,Tim Dewit,Party People,1ZvGInqvCALu6OxcGR4G5H,https://open.spotify.com/track/1ZvGInqvCALu6Ox...,6.0

In [3]:
df_wide.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78992 entries, 0 to 78991
Columns: 135 entries, tmdb_id to spotify_popularity
dtypes: bool(29), float64(16), int64(18), object(72)
memory usage: 66.1+ MB

In [7]:
df_above_500 = df_wide[df_wide['vote_count_above_500'] == True]
df_above_500 = df_above_500.sort_values(by=['film_vote_count'], ascending=False)
df_above_500

,tmdb_id,film_title,film_adult,film_runtime_min,film_genres,film_rating,film_vote_count,film_mpaa_rating,film_original_title,film_language_name,...,film_is_tv_movie,film_is_thriller,film_is_war,film_is_western,vote_count_above_500,composer_primary_clean,track_title_cleaned,spotify_track_id,spotify_url,spotify_popularity
4378,293660,Deadpool,False,108,"Action, Adventure, Comedy",7.623,32247,R,Deadpool,English,...,False,False,False,False,True,Tom Holkenborg,Liam Neeson Nightmares,6Dw3DgZxZaR5wnYR0Bvj7Z,https://open.spotify.com/track/6Dw3DgZxZaR5wnY...,22.0
4385,293660,Deadpool,False,108,"Action, Adventure, Comedy",7.623,32247,R,Deadpool,English,...,False,False,False,False,True,Tom Holkenborg,Going Commando,0cLcXcRsaYKyvDfoASYVbM,https://open.spotify.com/track/0cLcXcRsaYKyvDf...,21.0
4383,293660,Deadpool,False,108,"Action, Adventure, Comedy",7.623,32247,R,Deadpool,English,...,False,False,False,False,True,Tom Holkenborg,Four or Five Moments,54xdRclgMURz3qDo00y7V9,https://open.spotify.com/track/54xdRclgMURz3qD...,19.0
4382,293660,Deadpool,False,108,"Action, Adventure, Comedy",7.623,32247,R,Deadpool,English,...,False,False,False,False,True,Tom Holkenborg,Every Time I See Her,2IU1u9LAlJL9K9xcpw3LsR,https://open.spotify.com/track/2IU1u9LAlJL9K9x...,20.0
4381,293660,Deadpool,False,108,"Action, Adventure, Comedy",7.623,32247,R,Deadpool,English,...,False,False,False,False,True,Tom Holkenborg,Watership Down,70EFS9q2ms1hzi0Y3EV03p,https://open.spotify.com/track/70EFS9q2ms1hzi0...,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50994,864959,The Curse of Bridge Hollow,False,89,"Adventure, Comedy, Horror, Family",6.535,500,PG-13,The Curse of Bridge Hollow,English,...,False,False,False,False,True,Christopher Lennertz,Cemetery - Pictures,6eGhlrczicZplWMmfwLoYK,https://open.spotify.com/track/6eGhlrczicZplWM...,0.0
50993,864959,The Curse of Bridge Hollow,False,89,"Adventure, Comedy, Horror, Family",6.535,500,PG-13,The Curse of Bridge Hollow,English,...,False,False,False,False,True,Christopher Lennertz,Old Folks Home,1lgG477QMP0jKC1NGNdwat,https://open.spotify.com/track/1lgG477QMP0jKC1...,0.0
50992,864959,The Curse of Bridge Hollow,False,89,"Adventure, Comedy, Horror, Family",6.535,500,PG-13,The Curse of Bridge Hollow,English,...,False,False,False,False,True,Christopher Lennertz,Bridge Hollow,4aasmbvsZmcAc58YUDFVMW,https://open.spotify.com/track/4aasmbvsZmcAc58...,0.0
50991,864959,The Curse of Bridge Hollow,False,89,"Adventure, Comedy, Horror, Family",6.535,500,PG-13,The Curse of Bridge Hollow,English,...,False,False,False,False,True,Christopher Lennertz,Into the House,4uE5Tdas8vMeltVWKvdRxp,https://open.spotify.com/track/4uE5Tdas8vMeltV...,0.0
50988,864959,The Curse of Bridge Hollow,False,89,"Adventure, Comedy, Horror, Family",6.535,500,PG-13,The Curse of Bridge Hollow,English,...,False,False,False,False,True,Christopher Lennertz,Cast the Spell,3Gh7wKful10yIGC4coinf8,https://open.spotify.com/track/3Gh7wKful10yIGC...,0.0

In [8]:
len(df_above_500)

36580

In [9]:
# Create a column that has a unique identifier that can be used for de-bugging calls to the Soundnet API

df_above_500 = df_above_500.reset_index(drop=True)
df_above_500["soundnet_tracking_id"] = df_above_500.index
df_above_500.head()

,tmdb_id,film_title,film_adult,film_runtime_min,film_genres,film_rating,film_vote_count,film_mpaa_rating,film_original_title,film_language_name,...,film_is_thriller,film_is_war,film_is_western,vote_count_above_500,composer_primary_clean,track_title_cleaned,spotify_track_id,spotify_url,spotify_popularity,soundnet_tracking_id
0,293660,Deadpool,False,108,"Action, Adventure, Comedy",7.623,32247,R,Deadpool,English,...,False,False,False,True,Tom Holkenborg,Liam Neeson Nightmares,6Dw3DgZxZaR5wnYR0Bvj7Z,https://open.spotify.com/track/6Dw3DgZxZaR5wnY...,22.0,0
1,293660,Deadpool,False,108,"Action, Adventure, Comedy",7.623,32247,R,Deadpool,English,...,False,False,False,True,Tom Holkenborg,Going Commando,0cLcXcRsaYKyvDfoASYVbM,https://open.spotify.com/track/0cLcXcRsaYKyvDf...,21.0,1
2,293660,Deadpool,False,108,"Action, Adventure, Comedy",7.623,32247,R,Deadpool,English,...,False,False,False,True,Tom Holkenborg,Four or Five Moments,54xdRclgMURz3qDo00y7V9,https://open.spotify.com/track/54xdRclgMURz3qD...,19.0,2
3,293660,Deadpool,False,108,"Action, Adventure, Comedy",7.623,32247,R,Deadpool,English,...,False,False,False,True,Tom Holkenborg,Every Time I See Her,2IU1u9LAlJL9K9xcpw3LsR,https://open.spotify.com/track/2IU1u9LAlJL9K9x...,20.0,3
4,293660,Deadpool,False,108,"Action, Adventure, Comedy",7.623,32247,R,Deadpool,English,...,False,False,False,True,Tom Holkenborg,Watership Down,70EFS9q2ms1hzi0Y3EV03p,https://open.spotify.com/track/70EFS9q2ms1hzi0...,20.0,4

We ran the following code in a local environment to pull from Rapid API \(Soundnet\)\. Due to extremely slow API speeds and consistent errors, it was time\-prohibitive to recover 100% of the audio features we requested\. We called the API in several phases, attempting to improve our code in multiple iterations\. We will merge the CSVs from the various API runs here in the notebook\.

In [10]:
# CLIENT_SECRET = os.environ["RAPID_API_KEY"]

In [11]:
# # Test the API for single request

# test_id = '6EVxyHPACBrQjjql3g90gC'

# base_url = 'https://track-analysis.p.rapidapi.com/pktx/spotify/'

# url = base_url + str(test_id)

# headers = {
# 	"x-rapidapi-key": CLIENT_SECRET,
# 	"x-rapidapi-host": "track-analysis.p.rapidapi.com"
# }

# response = requests.get(url, headers=headers)

# print(response.json())

In [12]:
# """
# Soundnet Track Analysis API runner

# DROP-IN FRIENDLY VERSION (with accurate tqdm on resume)

# Key updates in this version
# ---------------------------
# ✅ Resume-aware tqdm:
#    - Computes how many rows in *this df* are already done (based on processed_ids)
#    - Starts tqdm with initial=already_done_in_df
#    - Does NOT pbar.update(1) for rows skipped due to resume

# ✅ Resume counters:
#    - already_in_outfile is now the number of UNIQUE spotify_id_used values in OUTFILE

# ✅ Optional clarity in tqdm postfix:
#    - Shows saved_run and saved_total

# Behavior summary
# ----------------
# 1) Iterates df (expects spotify_track_id per row)
# 2) Calls Soundnet Track Analysis API per track id
# 3) Writes append-only CSV with fixed schema
# 4) Supports resume by skipping spotify IDs already written
# 5) Handles rate limits / transient failures via retry/backoff/cooldown
# 6) Flushes partial batch on Ctrl+C or unexpected exceptions
# """

# # ============================================================
# # 0) INPUT: set the DataFrame you want to process
# # ============================================================

# df = df_above_500  # <- assumes this exists


# # ============================================================
# # 1) API configuration
# # ============================================================

# headers = {
#     "x-rapidapi-key": CLIENT_SECRET,  # <- assumes this exists
#     "x-rapidapi-host": "track-analysis.p.rapidapi.com",
# }
# base_url = "https://track-analysis.p.rapidapi.com/pktx/spotify/"


# # ============================================================
# # 2) Runtime parameters (tune these first)
# # ============================================================

# SLEEP_SECONDS = 0.15     # per-row sleep when not in cooldown
# TIMEOUT_SECONDS = 20     # request timeout
# BATCH_SIZE = 1000        # flush frequency
# OUTFILE = "Soundnet_run_0201_2.csv"  # append-only output file


# # ============================================================
# # 3) Retry / backoff / cooldown tuning
# # ============================================================

# MAX_RETRIES_429 = 4
# MAX_RETRIES_NET = 3
# BACKOFF_BASE = 1.0
# BACKOFF_CAP = 60.0
# JITTER = 0.25


# # ============================================================
# # 4) Session + in-run cache
# # ============================================================

# session = requests.Session()

# # Cache only successful results (so failures can recover if the ID repeats later)
# soundnet_cache = {}


# # ============================================================
# # 5) Output schema (fixed columns in fixed order)
# # ============================================================

# FIXED_COLS = [
#     "spotify_id_used",
#     "query_url",
#     "soundnet_tracking_id",
#     "film_title",
#     "recording_artist_credit",
#     "track_title_cleaned",
#     "cache_hit",
#     "error",
#     "error_type",
#     "status_code",
#     "retry_after",
#     "error_message",
#     "raw_json",
# ]


# def row_to_fixed_schema(
#     *,
#     spotify_id_used,
#     query_url,
#     soundnet_tracking_id,
#     film_title,
#     recording_artist_credit,
#     track_title_cleaned,
#     cache_hit,
#     payload,
#     status_code=None,
#     error=False,
#     error_type=None,
#     retry_after=None,
#     error_message=None,
# ):
#     """
#     Convert one API result (or error) into a dict matching FIXED_COLS.

#     - payload stored as JSON string in raw_json (safe for CSV).
#     - error fields provide consistent auditing.
#     """
#     try:
#         raw_json = json.dumps(payload, ensure_ascii=False)
#     except TypeError:
#         raw_json = json.dumps(str(payload), ensure_ascii=False)

#     return {
#         "spotify_id_used": spotify_id_used,
#         "query_url": query_url,
#         "soundnet_tracking_id": soundnet_tracking_id,
#         "film_title": film_title,
#         "recording_artist_credit": recording_artist_credit,
#         "track_title_cleaned": track_title_cleaned,
#         "cache_hit": bool(cache_hit),
#         "error": bool(error),
#         "error_type": error_type,
#         "status_code": status_code,
#         "retry_after": retry_after,
#         "error_message": error_message,
#         "raw_json": raw_json,
#     }


# def append_checkpoint(outpath, new_rows):
#     """
#     Append rows to OUTFILE using a fixed schema.

#     Safe to call repeatedly and safe to call on shutdown.
#     """
#     if not new_rows:
#         return

#     df_new = pd.DataFrame(new_rows)

#     # Ensure fixed columns exist + enforce order
#     for c in FIXED_COLS:
#         if c not in df_new.columns:
#             df_new[c] = pd.NA
#     df_new = df_new[FIXED_COLS]

#     write_header = not os.path.exists(outpath)
#     df_new.to_csv(outpath, index=False, mode="a", header=write_header)


# # ============================================================
# # 6) Resume support: skip IDs already written to OUTFILE
# # ============================================================

# processed_ids = set()
# already_in_outfile = 0  # unique ids already written

# if os.path.exists(OUTFILE):
#     try:
#         prev_ids = pd.read_csv(OUTFILE, usecols=["spotify_id_used"])
#         processed_ids = set(
#             str(x).strip()
#             for x in prev_ids["spotify_id_used"].dropna().tolist()
#             if str(x).strip() != ""
#         )
#         already_in_outfile = len(processed_ids)
#     except Exception:
#         processed_ids = set()
#         already_in_outfile = 0


# # ============================================================
# # 7) Metrics for tqdm (live health + progress)
# # ============================================================

# metrics = {
#     "saved_this_run": 0,
#     "ok": 0,
#     "missing_id": 0,
#     "cache_hit": 0,
#     "err_429": 0,
#     "err_http": 0,
#     "err_net": 0,
#     "err_unexpected": 0,
#     "retries_429": 0,
#     "retries_net": 0,
#     "sleep_seconds": 0.0,
#     "skipped_already_done": 0,
# }


# # ============================================================
# # 8) Sleep helpers (with accounting)
# # ============================================================

# cooldown_until = 0.0  # global cooldown timestamp (seconds since epoch)


# def _parse_retry_after(v):
#     """Parse Retry-After header if it's numeric seconds; otherwise return None."""
#     if v is None:
#         return None
#     try:
#         return float(v)
#     except Exception:
#         return None


# def _sleep_with_jitter(seconds):
#     """
#     Sleep with jitter and record time slept.

#     Jitter reduces synchronized bursts that can worsen rate limiting.
#     """
#     if seconds <= 0:
#         return
#     factor = 1.0 + random.uniform(-JITTER, JITTER)  # in [1-JITTER, 1+JITTER]
#     s = max(0.0, seconds * factor)
#     metrics["sleep_seconds"] += s
#     time.sleep(s)


# # ============================================================
# # 9) Progress bar + loop state (resume-aware)
# # ============================================================

# seen = 0
# batch_rows = []

# # Count how many rows in *this df* are already done, so tqdm starts correctly.
# if "spotify_track_id" in df.columns and processed_ids:
#     df_ids = df["spotify_track_id"].dropna().astype(str).str.strip()
#     already_done_in_df = int(df_ids.isin(processed_ids).sum())
# else:
#     already_done_in_df = 0

# pbar = tqdm(
#     total=len(df),
#     initial=already_done_in_df,
#     desc="Soundnet (rows processed)",
#     unit="row",
#     dynamic_ncols=True,
# )

# if already_in_outfile > 0:
#     pbar.write(
#         f"Resuming from {OUTFILE}: unique ids in outfile={already_in_outfile} | "
#         f"already_done_in_this_df={already_done_in_df}"
#     )


# # ============================================================
# # 10) Main loop
# # ============================================================

# stop_reason = None  # for final summary (e.g., "keyboard_interrupt", "exception", None)

# try:
#     for _, row in df.iterrows():
#         seen += 1

#         # ----------------------------
#         # 10.1) Extract identifiers + base fields
#         # ----------------------------
#         track_id = row.get("spotify_track_id")
#         track_id_str = None if pd.isna(track_id) else str(track_id).strip()
#         url = None if not track_id_str else (base_url + track_id_str)

#         # IMPORTANT: compute this BEFORE modifying processed_ids in this iteration
#         was_already_done = bool(track_id_str) and (track_id_str in processed_ids)

#         base_kwargs = dict(
#             spotify_id_used=track_id,
#             query_url=url,
#             soundnet_tracking_id=row.get("soundnet_tracking_id"),
#             film_title=row.get("film_title"),
#             recording_artist_credit=row.get("recording_artist_credit"),
#             track_title_cleaned=row.get("track_title_cleaned"),
#         )

#         # ----------------------------
#         # 10.2) Missing ID => write an error row (no API call)
#         # ----------------------------
#         if not track_id_str:
#             out_row = row_to_fixed_schema(
#                 **base_kwargs,
#                 cache_hit=False,
#                 payload=None,
#                 status_code=None,
#                 error=True,
#                 error_type="missing_spotify_track_id",
#                 retry_after=None,
#                 error_message="spotify_track_id was blank/NA",
#             )
#             batch_rows.append(out_row)
#             metrics["missing_id"] += 1
#             metrics["saved_this_run"] += 1

#         # ----------------------------
#         # 10.3) Already processed in a prior run => skip
#         # ----------------------------
#         elif was_already_done:
#             metrics["skipped_already_done"] += 1

#         # ----------------------------
#         # 10.4) Need to fetch (or cache hit)
#         # ----------------------------
#         else:
#             cached = soundnet_cache.get(track_id_str)
#             if cached is not None:
#                 # Cache hit (in-run): reuse successful stored row
#                 out_row = dict(cached)
#                 out_row["cache_hit"] = True
#                 metrics["cache_hit"] += 1

#             else:
#                 payload = None
#                 status_code = None
#                 retry_after = None
#                 error = False
#                 error_type = None
#                 error_message = None

#                 # Obey global cooldown before attempting
#                 now = time.time()
#                 if now < cooldown_until:
#                     _sleep_with_jitter(cooldown_until - now)

#                 attempt_429 = 0
#                 attempt_net = 0

#                 while True:
#                     try:
#                         response = session.get(url, headers=headers, timeout=TIMEOUT_SECONDS)
#                         status_code = response.status_code
#                         retry_after = response.headers.get("Retry-After")

#                         try:
#                             payload = response.json()
#                         except ValueError:
#                             payload = response.text

#                         # Success
#                         if status_code < 400:
#                             break

#                         # 429 rate limit => retry a few times
#                         if status_code == 429 and attempt_429 < MAX_RETRIES_429:
#                             attempt_429 += 1
#                             metrics["retries_429"] += 1

#                             ra = _parse_retry_after(retry_after)
#                             wait = ra if (ra is not None and ra > 0) else min(
#                                 BACKOFF_CAP, BACKOFF_BASE * (2 ** (attempt_429 - 1))
#                             )

#                             cooldown_until = max(cooldown_until, time.time() + wait)
#                             _sleep_with_jitter(wait)
#                             continue

#                         # Retry some 5xx as transient
#                         if 500 <= status_code < 600 and attempt_net < MAX_RETRIES_NET:
#                             attempt_net += 1
#                             metrics["retries_net"] += 1
#                             wait = min(BACKOFF_CAP, BACKOFF_BASE * (2 ** (attempt_net - 1)))
#                             _sleep_with_jitter(wait)
#                             continue

#                         # Terminal HTTP error
#                         error = True
#                         error_type = "rate_limited" if status_code == 429 else "http_error"
#                         break

#                     except (requests.exceptions.ConnectionError, requests.exceptions.Timeout) as e:
#                         # Retry transient network errors
#                         attempt_net += 1
#                         if attempt_net <= MAX_RETRIES_NET:
#                             metrics["retries_net"] += 1
#                             wait = min(BACKOFF_CAP, BACKOFF_BASE * (2 ** (attempt_net - 1)))
#                             _sleep_with_jitter(wait)
#                             continue

#                         # Terminal network error
#                         error = True
#                         error_type = "network_exception"
#                         error_message = str(e)
#                         payload = None
#                         break

#                     except Exception as e:
#                         # Terminal unexpected error
#                         error = True
#                         error_type = "unexpected_exception"
#                         error_message = repr(e)
#                         payload = None
#                         break

#                 out_row = row_to_fixed_schema(
#                     **base_kwargs,
#                     cache_hit=False,
#                     payload=payload,
#                     status_code=status_code,
#                     error=error,
#                     error_type=error_type,
#                     retry_after=retry_after,
#                     error_message=error_message,
#                 )

#                 if out_row["error"]:
#                     if out_row["error_type"] == "rate_limited":
#                         metrics["err_429"] += 1
#                     elif out_row["error_type"] == "http_error":
#                         metrics["err_http"] += 1
#                     elif out_row["error_type"] == "network_exception":
#                         metrics["err_net"] += 1
#                     else:
#                         metrics["err_unexpected"] += 1
#                 else:
#                     metrics["ok"] += 1

#                 # Cache successful results only
#                 if not out_row["error"]:
#                     soundnet_cache[track_id_str] = out_row

#             # Persist + mark processed for resume
#             batch_rows.append(out_row)
#             processed_ids.add(track_id_str)
#             metrics["saved_this_run"] += 1

#             # Per-row sleep (only when not already in cooldown)
#             if time.time() >= cooldown_until:
#                 _sleep_with_jitter(SLEEP_SECONDS)

#         # ----------------------------
#         # 10.5) Update progress bar
#         # ----------------------------
#         # Resume-aware: do NOT update the bar for rows that were already done,
#         # because pbar.initial already accounted for them.
#         if not was_already_done:
#             pbar.update(1)

#         if seen % 25 == 0:
#             cooldown_remaining = max(0.0, cooldown_until - time.time())
#             done_pct = (100.0 * pbar.n / pbar.total) if pbar.total else 0.0

#             pbar.set_postfix({
#                 "done_%": f"{done_pct:5.1f}%",
#                 "saved_run": metrics["saved_this_run"],
#                 "saved_total": already_in_outfile + metrics["saved_this_run"],
#                 "ok": metrics["ok"],
#                 "skip": metrics["skipped_already_done"],
#                 "429": metrics["err_429"],
#                 "http": metrics["err_http"],
#                 "net": metrics["err_net"],
#                 "r429": metrics["retries_429"],
#                 "rnet": metrics["retries_net"],
#                 "sleep_s": int(metrics["sleep_seconds"]),
#                 "cool_s": int(cooldown_remaining),
#                 "cache": metrics["cache_hit"],
#                 "miss": metrics["missing_id"],
#             })

#         # ----------------------------
#         # 10.6) Batch flush (regular checkpointing)
#         # ----------------------------
#         if len(batch_rows) >= BATCH_SIZE:
#             append_checkpoint(OUTFILE, batch_rows)
#             batch_rows.clear()
#             pbar.write(f"Flushed batch ({BATCH_SIZE}). saved_this_run={metrics['saved_this_run']}")

# except KeyboardInterrupt:
#     stop_reason = "keyboard_interrupt"
#     pbar.write("KeyboardInterrupt received — flushing partial batch to disk and stopping...")

# except Exception as e:
#     stop_reason = f"exception: {repr(e)}"
#     pbar.write(f"Unexpected exception — flushing partial batch to disk and stopping...\n{repr(e)}")

# finally:
#     # ALWAYS flush remaining rows and close progress bar cleanly
#     if batch_rows:
#         try:
#             append_checkpoint(OUTFILE, batch_rows)
#             pbar.write(f"Final flush complete: wrote {len(batch_rows)} rows from partial batch.")
#         except Exception as flush_err:
#             pbar.write(f"ERROR: Final flush failed: {repr(flush_err)}")
#         finally:
#             batch_rows.clear()

#     pbar.close()

#     if stop_reason is None:
#         stop_reason = "completed"

#     print(
#         f"Done ({stop_reason}). Input rows iterated={seen}/{len(df)} | "
#         f"saved_this_run={metrics['saved_this_run']} | ok={metrics['ok']} | "
#         f"skipped_already_done={metrics['skipped_already_done']} | "
#         f"429={metrics['err_429']} http={metrics['err_http']} net={metrics['err_net']} "
#         f"missing_id={metrics['missing_id']} cache_hit={metrics['cache_hit']} | "
#         f"retries_429={metrics['retries_429']} retries_net={metrics['retries_net']} | "
#         f"sleep_seconds≈{metrics['sleep_seconds']:.1f} | "
#         f"already_done_in_this_df={already_done_in_df} unique_ids_in_outfile={already_in_outfile}"
#     )

In [13]:
filepath = '/work/api_dumps/4.4.rapid_api_track_parts/07_Soundnet_run_0201_2.csv'
df_final_results = pd.read_csv(filepath)

print(f"Total records in final batch: {df_final_results.shape[0]}")
df_final_results.head()

Total records in final batch: 17533

,spotify_id_used,query_url,soundnet_tracking_id,film_title,recording_artist_credit,track_title_cleaned,cache_hit,error,error_type,status_code,retry_after,error_message,raw_json
0,2sOjF9izGpI0O5r3fjDUlm,https://track-analysis.p.rapidapi.com/pktx/spo...,19143,Dora and the Lost City of Gold,John Debney & Germaine Franco,Alejandro's Gold,False,False,NaN,200.0,NaN,NaN,"{""id"": ""7a64f512fd90ffe6309032b214513c6f"", ""ke..."
1,6lIkN7Y5HZZYGwhmt8fs2F,https://track-analysis.p.rapidapi.com/pktx/spo...,19144,Dora and the Lost City of Gold,John Debney & Germaine Franco,First Day of School,False,False,NaN,200.0,NaN,NaN,"{""id"": ""f58ed2acfe38daf1605e7f0de9fe249b"", ""ke..."
2,2YyBMQRgOPrgRRtTfr8ZP6,https://track-analysis.p.rapidapi.com/pktx/spo...,19145,Dora and the Lost City of Gold,John Debney & Germaine Franco,Moon Gate,False,False,NaN,200.0,NaN,NaN,"{""id"": ""d68d7401c4a778ca40b6cf84d0cd55cf"", ""ke..."
3,2zLEHUtcsiDkGyBMOYGVRs,https://track-analysis.p.rapidapi.com/pktx/spo...,19146,Dora and the Lost City of Gold,John Debney & Germaine Franco,Am I a Weirdo,False,False,NaN,200.0,NaN,NaN,"{""id"": ""dde99d027c5483dc72c1ca4c0b3aed45"", ""ke..."
4,2dIqxzKX1qYk3NmDv07V52,https://track-analysis.p.rapidapi.com/pktx/spo...,19147,Dora and the Lost City of Gold,John Debney & Germaine Franco,Parapata Vista,False,False,NaN,200.0,NaN,NaN,"{""id"": ""f5561b4874c032a9720c57fe2536a011"", ""ke..."

In [14]:
# We changed our schema to record the API results mid-way through in order to improve de-bugging. 
# Here, we are loading in the result files that contained the final schema.

files = [
    "/work/api_dumps/4.4.rapid_api_track_parts/02_Soundnet_Results.csv",
    "/work/api_dumps/4.4.rapid_api_track_parts/03_Soundnet_Results.csv",
    "/work/api_dumps/4.4.rapid_api_track_parts/04_Soundnet_minimal_sleep_batches_run_INCOMPLETE_0129.csv",
    "/work/api_dumps/4.4.rapid_api_track_parts/05_Soundnet_missing_audio_features_0131_2.csv",
    "/work/api_dumps/4.4.rapid_api_track_parts/06_Successful Results from Jaime and Khurram.csv",
    "/work/api_dumps/4.4.rapid_api_track_parts/07_Soundnet_run_0201_2.csv"
]

dfs = [pd.read_csv(f) for f in files]
combined_df = pd.concat(dfs, ignore_index=True)

print(f"Total records after concatenation: {combined_df.shape[0]}")
combined_df.head()

Total records after concatenation: 35724

,spotify_id_used,query_url,soundnet_tracking_id,film_title,recording_artist_credit,track_title_cleaned,cache_hit,error,error_type,status_code,retry_after,error_message,raw_json
0,3filDKRRDJXRWB2qoBNcPN,https://track-analysis.p.rapidapi.com/pktx/spo...,6847,The 5th Wave,Henry Jackman,Epilogue,False,False,NaN,200.0,NaN,NaN,"{""id"": ""9f952ab566b47a9b2b79c9bc57cb5b7d"", ""ke..."
1,3VMdjpQ6FdannAgCcCYSb5,https://track-analysis.p.rapidapi.com/pktx/spo...,6848,The 5th Wave,Henry Jackman,5th Wave,False,False,NaN,200.0,NaN,NaN,"{""id"": ""b193bb0e52e39c68cf92fa32d4bfd77f"", ""ke..."
2,7jTsGHs9uxcypdQWg5uVuU,https://track-analysis.p.rapidapi.com/pktx/spo...,6849,The 5th Wave,Henry Jackman,The Others,False,False,NaN,200.0,NaN,NaN,"{""id"": ""f2e50d3efebc0103430ea2265a4c5ab6"", ""ke..."
3,33Zga4y9zokD77oxzZg3nQ,https://track-analysis.p.rapidapi.com/pktx/spo...,6850,The 5th Wave,Henry Jackman,One Degree of Separation,False,False,NaN,200.0,NaN,NaN,"{""id"": ""65f178e370a1f68d56cac5acff0a5bcb"", ""ke..."
4,43uoMMAVO0PNOCtEPl0a2l,https://track-analysis.p.rapidapi.com/pktx/spo...,6851,The 5th Wave,Henry Jackman,Under Fire,False,False,NaN,200.0,NaN,NaN,"{""id"": ""cc6a95bbfe529057cc4f54af8394b12c"", ""ke..."

In [15]:
# -------------------------------------------------
# Drop rows with API errors
# -------------------------------------------------

combined_df = combined_df[combined_df["error"] == False].copy()
combined_df = combined_df[
    ~combined_df["raw_json"].astype("string").str.contains("error", case=False, na=False)
].copy()

print(f"Total records in these batches after dropping errors: {combined_df.shape[0]}")

# -------------------------------------------------
# Parse raw JSON with explicit parse-success flag
# -------------------------------------------------

def safe_json_load_with_ok(x):
    if pd.isna(x) or x == "":
        return {}, True
    if isinstance(x, dict):
        return x, True
    try:
        return json.loads(x), True
    except Exception:
        return {}, False

parsed = combined_df["raw_json"].apply(safe_json_load_with_ok)

combined_df["raw_json_parsed"] = parsed.apply(lambda t: t[0])
combined_df["json_parse_ok"] = parsed.apply(lambda t: t[1])

# -------------------------------------------------
# Explode JSON into columns
# -------------------------------------------------

# Explode JSON into columns (force same index as combined_df)
features_df = (
    pd.json_normalize(combined_df["raw_json_parsed"])
    .set_index(combined_df.index)   # <- force alignment
    .drop(columns=["error"], errors="ignore")
)

# Join back to original dataframe
df_exploded = (
    combined_df
    .drop(columns=["raw_json"])
    .join(features_df)
)

# Backfill key directly from raw_json_parsed where key is missing/blank
key_s = df_exploded["key"].astype("string")
mask_without_key = key_s.isna() | (key_s.str.strip() == "")

df_exploded.loc[mask_without_key, "key"] = df_exploded.loc[mask_without_key, "raw_json_parsed"].apply(
    lambda d: d.get("key") if isinstance(d, dict) else None
)

# Re-check
key_s2 = df_exploded["key"].astype("string")
mask_without_key2 = key_s2.isna() | (key_s2.str.strip() == "")

print(f"Count without key (after backfill): {mask_without_key2.sum()}")
rows_without_key = df_exploded.loc[mask_without_key2]
rows_without_key

Total records in these batches after dropping errors: 26243
Count without key (after backfill): 136

,spotify_id_used,query_url,soundnet_tracking_id,film_title,recording_artist_credit,track_title_cleaned,cache_hit,error,error_type,status_code,...,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness,name,album
187,46Ch2Sj3pZrtfbkyDOGU6h,https://track-analysis.p.rapidapi.com/pktx/spo...,7061,The Equalizer 2,Harry Gregson‐Williams,Five Stars for Amy,False,False,NaN,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,5qHBXlA4UZPEisKdgBuwDG,https://track-analysis.p.rapidapi.com/pktx/spo...,7100,Southpaw,James Horner,Suicidal Rampage,False,False,NaN,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,2QucTxd7ycUJuaTVmmgh2N,https://track-analysis.p.rapidapi.com/pktx/spo...,7114,Southpaw,James Horner,Dream Crusher,False,False,NaN,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,43YFYprzUru4CKaSLVsQ3Q,https://track-analysis.p.rapidapi.com/pktx/spo...,7117,Southpaw,James Horner,Hope vs Escobar,False,False,NaN,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,2DsBubAljqcii9G8DWsBh1,https://track-analysis.p.rapidapi.com/pktx/spo...,7144,The Wild Robot,Kris Bowers,The Island,False,False,NaN,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35604,63oRjDDcQdt4oq5m5WjKPb,https://track-analysis.p.rapidapi.com/pktx/spo...,36459,Hellboy: The Crooked Man,Sven Faulconer,Cora's Skin,False,False,NaN,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35616,6i3U9BmaezDWwzQM1IUZ3u,https://track-analysis.p.rapidapi.com/pktx/spo...,36471,Hellboy: The Crooked Man,Sven Faulconer,I Used the Lucky Bone,False,False,NaN,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35633,4XXuyi5LKCOm25q64H73PE,https://track-analysis.p.rapidapi.com/pktx/spo...,36488,Hellboy: The Crooked Man,Sven Faulconer,Sinners,False,False,NaN,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35696,6eGhlrczicZplWMmfwLoYK,https://track-analysis.p.rapidapi.com/pktx/spo...,36551,The Curse of Bridge Hollow,Christopher Lennertz,Cemetery - Pictures,False,False,NaN,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35721,34zacsJXmjLRNqs7g8NfSs,https://track-analysis.p.rapidapi.com/pktx/spo...,36577,The Curse of Bridge Hollow,Christopher Lennertz,Tomb Spell,False,False,NaN,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
has_key_in_dict = df_exploded["raw_json_parsed"].apply(lambda d: isinstance(d, dict) and ("key" in d))
missing_key_col  = df_exploded["key"].astype("string").isna()

print("Dict has 'key' but column is NA:", (has_key_in_dict & missing_key_col).sum())

Dict has 'key' but column is NA: 0

In [17]:
# Load the results gathered under the prior schema

filepath = '/work/api_dumps/4.4.rapid_api_track_parts/01_Soundnet_Results.csv'
df_1 = pd.read_csv(filepath)

print(f"Total records in df 1: {df_1.shape[0]}")
df_1.head()

Total records in df 1: 6250

,id,key,mode,camelot,tempo,duration,popularity,energy,danceability,happiness,...,speechiness,loudness,cache_hit,recording_artist_credit,track_title_cleaned,spotify_id_used,query_url,soundnet_tracking_id,name,album
0,cb2a938672ef65170919b059143430fe,Bb,major,6B,83.0,6:50,19.0,12.0,17.0,3.0,...,4.0,-24 dB,False,Tom Holkenborg,This Place Looks Sanitary,6c94SDLrydgXbBEyliOfrQ,https://track-analysis.p.rapidapi.com/pktx/spo...,0,NaN,NaN
1,96142ef53a749e2deac964316f9435cb,Ab,major,4B,76.0,4:10,66.0,31.0,45.0,34.0,...,3.0,-9 dB,False,Juice Newton,Angel of the Morning,11y8GSP2ASv8S9n0FiiDva,https://track-analysis.p.rapidapi.com/pktx/spo...,1,NaN,NaN
2,9dd4e9b02e480024f6eb082a9a5e3bfb,D,minor,7A,76.0,2:32,21.0,23.0,12.0,3.0,...,4.0,-13 dB,False,Tom Holkenborg,Easy Angel,6EVxyHPACBrQjjql3g90gC,https://track-analysis.p.rapidapi.com/pktx/spo...,2,NaN,NaN
3,2ad2fb81b246d8fc387d5262d956d545,A,major,11B,145.0,3:47,54.0,25.0,45.0,18.0,...,3.0,-9 dB,False,Tom Holkenborg,Man in a Red Suit,6akjHxUud7gCF4vJfwSXJ2,https://track-analysis.p.rapidapi.com/pktx/spo...,3,NaN,NaN
4,dbf0aed0c1a747635394edb8105ebafb,C,major,8B,97.0,4:09,72.0,67.0,94.0,79.0,...,21.0,-7 dB,False,Salt‐N‐Pepa,Shoop,0Pu71wxadDlB8fJXfjIjeJ,https://track-analysis.p.rapidapi.com/pktx/spo...,4,NaN,NaN

In [18]:
# Drop empty results from this batch

df_1 = df_1[df_1["key"].notna() & (df_1["key"].str.strip() != "")]

print(f"Total records in df_1 after dropping empty results: {df_1.shape[0]}")
df_1.head()

Total records in df_1 after dropping empty results: 6209

,id,key,mode,camelot,tempo,duration,popularity,energy,danceability,happiness,...,speechiness,loudness,cache_hit,recording_artist_credit,track_title_cleaned,spotify_id_used,query_url,soundnet_tracking_id,name,album
0,cb2a938672ef65170919b059143430fe,Bb,major,6B,83.0,6:50,19.0,12.0,17.0,3.0,...,4.0,-24 dB,False,Tom Holkenborg,This Place Looks Sanitary,6c94SDLrydgXbBEyliOfrQ,https://track-analysis.p.rapidapi.com/pktx/spo...,0,NaN,NaN
1,96142ef53a749e2deac964316f9435cb,Ab,major,4B,76.0,4:10,66.0,31.0,45.0,34.0,...,3.0,-9 dB,False,Juice Newton,Angel of the Morning,11y8GSP2ASv8S9n0FiiDva,https://track-analysis.p.rapidapi.com/pktx/spo...,1,NaN,NaN
2,9dd4e9b02e480024f6eb082a9a5e3bfb,D,minor,7A,76.0,2:32,21.0,23.0,12.0,3.0,...,4.0,-13 dB,False,Tom Holkenborg,Easy Angel,6EVxyHPACBrQjjql3g90gC,https://track-analysis.p.rapidapi.com/pktx/spo...,2,NaN,NaN
3,2ad2fb81b246d8fc387d5262d956d545,A,major,11B,145.0,3:47,54.0,25.0,45.0,18.0,...,3.0,-9 dB,False,Tom Holkenborg,Man in a Red Suit,6akjHxUud7gCF4vJfwSXJ2,https://track-analysis.p.rapidapi.com/pktx/spo...,3,NaN,NaN
4,dbf0aed0c1a747635394edb8105ebafb,C,major,8B,97.0,4:09,72.0,67.0,94.0,79.0,...,21.0,-7 dB,False,Salt‐N‐Pepa,Shoop,0Pu71wxadDlB8fJXfjIjeJ,https://track-analysis.p.rapidapi.com/pktx/spo...,4,NaN,NaN

In [19]:
# Re-order the columns to match the final schema

col_order = [
    'spotify_id_used',
    'query_url',
    'soundnet_tracking_id',
    'recording_artist_credit',
    'track_title_cleaned',
    'cache_hit',
    'id',
    'key',
    'mode',
    'camelot',
    'tempo',
    'duration',
    'popularity',
    'energy',
    'danceability',
    'happiness',
    'acousticness',
    'instrumentalness',
    'liveness',
    'speechiness',
    'loudness',
    'name',
    'album'
 ]

df_1 = df_1[col_order]
df_1.head()

,spotify_id_used,query_url,soundnet_tracking_id,recording_artist_credit,track_title_cleaned,cache_hit,id,key,mode,camelot,...,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness,name,album
0,6c94SDLrydgXbBEyliOfrQ,https://track-analysis.p.rapidapi.com/pktx/spo...,0,Tom Holkenborg,This Place Looks Sanitary,False,cb2a938672ef65170919b059143430fe,Bb,major,6B,...,12.0,17.0,3.0,77.0,89.0,55.0,4.0,-24 dB,NaN,NaN
1,11y8GSP2ASv8S9n0FiiDva,https://track-analysis.p.rapidapi.com/pktx/spo...,1,Juice Newton,Angel of the Morning,False,96142ef53a749e2deac964316f9435cb,Ab,major,4B,...,31.0,45.0,34.0,43.0,0.0,8.0,3.0,-9 dB,NaN,NaN
2,6EVxyHPACBrQjjql3g90gC,https://track-analysis.p.rapidapi.com/pktx/spo...,2,Tom Holkenborg,Easy Angel,False,9dd4e9b02e480024f6eb082a9a5e3bfb,D,minor,7A,...,23.0,12.0,3.0,12.0,82.0,12.0,4.0,-13 dB,NaN,NaN
3,6akjHxUud7gCF4vJfwSXJ2,https://track-analysis.p.rapidapi.com/pktx/spo...,3,Tom Holkenborg,Man in a Red Suit,False,2ad2fb81b246d8fc387d5262d956d545,A,major,11B,...,25.0,45.0,18.0,88.0,0.0,14.0,3.0,-9 dB,NaN,NaN
4,0Pu71wxadDlB8fJXfjIjeJ,https://track-analysis.p.rapidapi.com/pktx/spo...,4,Salt‐N‐Pepa,Shoop,False,dbf0aed0c1a747635394edb8105ebafb,C,major,8B,...,67.0,94.0,79.0,9.0,0.0,6.0,21.0,-7 dB,NaN,NaN

In [20]:
# Concatenate the dataframes into one schema

final_schema_df = pd.concat([df_exploded, df_1], ignore_index=True)

print(f"Total records after concatenating all results, all schemas: {final_schema_df.shape[0]}")
final_schema_df.head()

Total records after concatenating all results, all schemas: 32452

,spotify_id_used,query_url,soundnet_tracking_id,film_title,recording_artist_credit,track_title_cleaned,cache_hit,error,error_type,status_code,...,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness,name,album
0,3filDKRRDJXRWB2qoBNcPN,https://track-analysis.p.rapidapi.com/pktx/spo...,6847,The 5th Wave,Henry Jackman,Epilogue,False,False,NaN,200.0,...,12.0,20.0,3.0,46.0,96.0,53.0,4.0,-16 dB,NaN,NaN
1,3VMdjpQ6FdannAgCcCYSb5,https://track-analysis.p.rapidapi.com/pktx/spo...,6848,The 5th Wave,Henry Jackman,5th Wave,False,False,NaN,200.0,...,4.0,13.0,4.0,99.0,95.0,8.0,4.0,-32 dB,NaN,NaN
2,7jTsGHs9uxcypdQWg5uVuU,https://track-analysis.p.rapidapi.com/pktx/spo...,6849,The 5th Wave,Henry Jackman,The Others,False,False,NaN,200.0,...,37.0,30.0,4.0,27.0,87.0,11.0,5.0,-14 dB,NaN,NaN
3,33Zga4y9zokD77oxzZg3nQ,https://track-analysis.p.rapidapi.com/pktx/spo...,6850,The 5th Wave,Henry Jackman,One Degree of Separation,False,False,NaN,200.0,...,91.0,67.0,75.0,10.0,0.0,29.0,6.0,-4 dB,NaN,NaN
4,43uoMMAVO0PNOCtEPl0a2l,https://track-analysis.p.rapidapi.com/pktx/spo...,6851,The 5th Wave,Henry Jackman,Under Fire,False,False,NaN,200.0,...,57.0,62.0,61.0,7.0,0.0,34.0,6.0,-8 dB,NaN,NaN

In [22]:
# Rename spotify id column to make joining easier

final_schema_df = final_schema_df.rename(
    columns={"spotify_id_used": "spotify_track_id"}
)

In [23]:
# De-duplicate on artist-track before merging (if duplicates found, keep row with lowest Spotify ID)

final_schema_deduped_df = (
    final_schema_df
    .sort_values("spotify_track_id")  
    .drop_duplicates(
        subset=["recording_artist_credit", "track_title_cleaned"],
        keep="first"
    )
)

print(f"Number of records after de-dupe: {len(final_schema_deduped_df)}")
final_schema_deduped_df.head()

Number of records after de-dupe: 32065

,spotify_track_id,query_url,soundnet_tracking_id,film_title,recording_artist_credit,track_title_cleaned,cache_hit,error,error_type,status_code,...,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness,name,album
2161,002dozOGSO8AhuXoz7kDZT,https://track-analysis.p.rapidapi.com/pktx/spo...,9188,Steve Jobs,Daniel Pemberton,It's an Abstract,False,False,NaN,200.0,...,80.0,55.0,55.0,0.0,0.0,8.0,5.0,-7 dB,NaN,NaN
4955,003vvx7Niy0yvhvHt4a68B,https://track-analysis.p.rapidapi.com/pktx/spo...,14126,Saltburn,The Killers,Mr. Brightside,False,False,NaN,200.0,...,91.0,35.0,24.0,0.0,0.0,10.0,7.0,-5 dB,NaN,NaN
25029,005xfoYaMudYZUwbq5GrVc,https://track-analysis.p.rapidapi.com/pktx/spo...,35048,The Life Ahead,Gabriel Yared,Madame Rosa,False,False,NaN,200.0,...,17.0,14.0,6.0,53.0,20.0,16.0,4.0,-19 dB,NaN,NaN
26071,005yTjf6DSZIBq8PVAF1Pc,https://track-analysis.p.rapidapi.com/pktx/spo...,36277,In Darkness,Niall Byrne,Sofia's Theme,False,False,NaN,200.0,...,4.0,19.0,6.0,99.0,78.0,9.0,5.0,-27 dB,NaN,NaN
31175,006Usl1ICbBs6LcQ5D9NjP,https://track-analysis.p.rapidapi.com/pktx/spo...,5447,NaN,Abel Korzeniowski,Veiled Mirrors,False,NaN,NaN,NaN,...,0.0,42.0,23.0,100.0,94.0,10.0,5.0,-35 dB,NaN,NaN

In [24]:
# Checking for spotify_track_id duplicates after de-duping on artist-track

final_schema_deduped_df["spotify_track_id"].value_counts()[lambda s: s > 1]

spotify_track_id
5bKP0HAlVAzKVqBR3ZjFE6    3
5cdx6h6N1E4PwKkOwb8Gzl    3
6LuO639cKBsWAl3eky6shf    2
2kfyCVwpNexatN2NckQ34y    2
1z5gnDV9Q5SOXAk6KWFHID    2
                         ..
4lzI0OwzIQ8gdkQNAz8MFO    2
3v5Zm0ebcx6nNaFojght81    2
0q21FNwES2bbtcduB6kjEU    2
0HoiPnX9uLXqb3BuTJuabG    2
0O0AGwdgXj7BAdl2KAdV4W    2
Name: count, Length: 149, dtype: int64

In [25]:
# Examine rows with remaining duplicate spotify_track_id's

duplicate_rows = final_schema_deduped_df[
    final_schema_deduped_df["spotify_track_id"].duplicated(keep=False)
].sort_values("spotify_track_id")

print(f"Number of rows with duplicate Spotify ID's: {len(duplicate_rows)}")
duplicate_rows

Number of rows with duplicate Spotify ID's: 300

,spotify_track_id,query_url,soundnet_tracking_id,film_title,recording_artist_credit,track_title_cleaned,cache_hit,error,error_type,status_code,...,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness,name,album
15936,091d5SFZ7xtM8QV6LLgnBr,https://track-analysis.p.rapidapi.com/pktx/spo...,23125,Jolt,Dominic Lewis,V,False,False,NaN,200.0,...,54.0,43.0,11.0,0.0,0.0,7.0,3.0,-9 dB,NaN,NaN
4179,091d5SFZ7xtM8QV6LLgnBr,https://track-analysis.p.rapidapi.com/pktx/spo...,11573,The Fall Guy,YUNGBLUD & Dominic Lewis,I Was Made for Lovin' You (From the Fall Guy) ...,False,False,NaN,200.0,...,54.0,43.0,11.0,0.0,0.0,7.0,3.0,-9 dB,NaN,NaN
11095,09FpvC1Jcec84kxHvHizJZ,https://track-analysis.p.rapidapi.com/pktx/spo...,20904,The Conjuring: Last Rites,Benjamin Wallfisch,Proposal,False,False,NaN,200.0,...,69.0,89.0,22.0,5.0,0.0,61.0,7.0,-5 dB,NaN,NaN
28791,09FpvC1Jcec84kxHvHizJZ,https://track-analysis.p.rapidapi.com/pktx/spo...,2829,NaN,"Hans Zimmer, Pharrell Williams & Benjamin Wall...",Proposal,False,NaN,NaN,NaN,...,69.0,89.0,22.0,5.0,0.0,61.0,7.0,-5 dB,NaN,NaN
27791,0HABZM5IsewSechndZ5899,https://track-analysis.p.rapidapi.com/pktx/spo...,1737,NaN,Alexandre Desplat,Watching Ruth,False,NaN,NaN,NaN,...,8.0,34.0,5.0,93.0,90.0,12.0,4.0,-18 dB,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27431,7q9DWirqkFFZDzNagf7esc,https://track-analysis.p.rapidapi.com/pktx/spo...,1332,NaN,Hans Zimmer,Ornithopter,False,NaN,NaN,NaN,...,70.0,33.0,4.0,0.0,65.0,12.0,4.0,-14 dB,NaN,NaN
28864,7rTPLQt7vgWmexf1Axop4L,https://track-analysis.p.rapidapi.com/pktx/spo...,2903,NaN,Brian Tyler,The Super Mario Brothers,False,NaN,NaN,NaN,...,40.0,17.0,7.0,87.0,88.0,61.0,4.0,-9 dB,NaN,NaN
30638,7rTPLQt7vgWmexf1Axop4L,https://track-analysis.p.rapidapi.com/pktx/spo...,4878,NaN,Brian Tyler,Brother,True,NaN,NaN,NaN,...,40.0,17.0,7.0,87.0,88.0,61.0,4.0,-9 dB,NaN,NaN
12243,7xdRysaxO6KApNwdNWaIS8,https://track-analysis.p.rapidapi.com/pktx/spo...,28456,Missing Link,Carter Burwell,Climbing,False,False,NaN,200.0,...,11.0,24.0,5.0,41.0,85.0,11.0,4.0,-14 dB,NaN,NaN
17043,7xdRysaxO6KApNwdNWaIS8,https://track-analysis.p.rapidapi.com/pktx/spo...,24464,To Catch a Killer,Carter Burwell & Forrest Gray,Climbing Mountains of Trash,False,False,NaN,200.0,...,11.0,24.0,5.0,41.0,85.0,11.0,4.0,-14 dB,NaN,NaN

In [26]:
# Drop extraneous columns

final_schema_deduped_df = final_schema_deduped_df.drop(columns=["name", "album"])
final_schema_deduped_df.head()

,spotify_track_id,query_url,soundnet_tracking_id,film_title,recording_artist_credit,track_title_cleaned,cache_hit,error,error_type,status_code,...,duration,popularity,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness
2161,002dozOGSO8AhuXoz7kDZT,https://track-analysis.p.rapidapi.com/pktx/spo...,9188,Steve Jobs,Daniel Pemberton,It's an Abstract,False,False,NaN,200.0,...,4:05,36.0,80.0,55.0,55.0,0.0,0.0,8.0,5.0,-7 dB
4955,003vvx7Niy0yvhvHt4a68B,https://track-analysis.p.rapidapi.com/pktx/spo...,14126,Saltburn,The Killers,Mr. Brightside,False,False,NaN,200.0,...,3:43,91.0,91.0,35.0,24.0,0.0,0.0,10.0,7.0,-5 dB
25029,005xfoYaMudYZUwbq5GrVc,https://track-analysis.p.rapidapi.com/pktx/spo...,35048,The Life Ahead,Gabriel Yared,Madame Rosa,False,False,NaN,200.0,...,4:00,5.0,17.0,14.0,6.0,53.0,20.0,16.0,4.0,-19 dB
26071,005yTjf6DSZIBq8PVAF1Pc,https://track-analysis.p.rapidapi.com/pktx/spo...,36277,In Darkness,Niall Byrne,Sofia's Theme,False,False,NaN,200.0,...,1:02,6.0,4.0,19.0,6.0,99.0,78.0,9.0,5.0,-27 dB
31175,006Usl1ICbBs6LcQ5D9NjP,https://track-analysis.p.rapidapi.com/pktx/spo...,5447,NaN,Abel Korzeniowski,Veiled Mirrors,False,NaN,NaN,NaN,...,2:52,71.0,0.0,42.0,23.0,100.0,94.0,10.0,5.0,-35 dB

In [27]:
list(final_schema_deduped_df.columns)

['spotify_track_id',
 'query_url',
 'soundnet_tracking_id',
 'film_title',
 'recording_artist_credit',
 'track_title_cleaned',
 'cache_hit',
 'error',
 'error_type',
 'status_code',
 'retry_after',
 'error_message',
 'raw_json_parsed',
 'json_parse_ok',
 'id',
 'key',
 'mode',
 'camelot',
 'tempo',
 'duration',
 'popularity',
 'energy',
 'danceability',
 'happiness',
 'acousticness',
 'instrumentalness',
 'liveness',
 'speechiness',
 'loudness']

In [28]:
print(f"Number of records before merging into wide dataframe: {len(final_schema_deduped_df)}")
final_schema_deduped_df.head()

Number of records before merging into wide dataframe: 32065

,spotify_track_id,query_url,soundnet_tracking_id,film_title,recording_artist_credit,track_title_cleaned,cache_hit,error,error_type,status_code,...,duration,popularity,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness
2161,002dozOGSO8AhuXoz7kDZT,https://track-analysis.p.rapidapi.com/pktx/spo...,9188,Steve Jobs,Daniel Pemberton,It's an Abstract,False,False,NaN,200.0,...,4:05,36.0,80.0,55.0,55.0,0.0,0.0,8.0,5.0,-7 dB
4955,003vvx7Niy0yvhvHt4a68B,https://track-analysis.p.rapidapi.com/pktx/spo...,14126,Saltburn,The Killers,Mr. Brightside,False,False,NaN,200.0,...,3:43,91.0,91.0,35.0,24.0,0.0,0.0,10.0,7.0,-5 dB
25029,005xfoYaMudYZUwbq5GrVc,https://track-analysis.p.rapidapi.com/pktx/spo...,35048,The Life Ahead,Gabriel Yared,Madame Rosa,False,False,NaN,200.0,...,4:00,5.0,17.0,14.0,6.0,53.0,20.0,16.0,4.0,-19 dB
26071,005yTjf6DSZIBq8PVAF1Pc,https://track-analysis.p.rapidapi.com/pktx/spo...,36277,In Darkness,Niall Byrne,Sofia's Theme,False,False,NaN,200.0,...,1:02,6.0,4.0,19.0,6.0,99.0,78.0,9.0,5.0,-27 dB
31175,006Usl1ICbBs6LcQ5D9NjP,https://track-analysis.p.rapidapi.com/pktx/spo...,5447,NaN,Abel Korzeniowski,Veiled Mirrors,False,NaN,NaN,NaN,...,2:52,71.0,0.0,42.0,23.0,100.0,94.0,10.0,5.0,-35 dB

In [29]:
# Check for duplicate keys before merging

assert not final_schema_deduped_df.duplicated(
    subset=[
        "spotify_track_id",
        "recording_artist_credit",
        "track_title_cleaned",
    ]
).any(), "Duplicate composite keys in final_schema_deduped_df"

In [30]:
# Merge audio features into df_wide

cols_to_add = [
    "spotify_track_id",
    "recording_artist_credit",
    "track_title_cleaned",
    "key",
    "mode",
    "camelot",
    "tempo",
    "duration",
    "popularity",
    "energy",
    "danceability",
    "happiness",
    "acousticness",
    "instrumentalness",
    "liveness",
    "speechiness",
    "loudness",
]

df_wide = df_wide.merge(
    final_schema_deduped_df[cols_to_add],
    on=[
        "spotify_track_id",
        "recording_artist_credit",
        "track_title_cleaned",
    ],
    how="left"
)

print(f"Number of records after merging: {len(df_wide)}")
df_wide.head()

Number of records after merging: 78992

,tmdb_id,film_title,film_adult,film_runtime_min,film_genres,film_rating,film_vote_count,film_mpaa_rating,film_original_title,film_language_name,...,duration,popularity,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness
0,1027160,Alone in the Dark,False,90,"Horror, Thriller",4.769,13,NR,Alone in the Dark,English,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1027160,Alone in the Dark,False,90,"Horror, Thriller",4.769,13,NR,Alone in the Dark,English,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df_wide.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78992 entries, 0 to 78991
Columns: 149 entries, tmdb_id to loudness
dtypes: bool(29), float64(25), int64(18), object(77)
memory usage: 74.5+ MB

In [32]:
list(df_wide.columns)

['tmdb_id',
 'film_title',
 'film_adult',
 'film_runtime_min',
 'film_genres',
 'film_rating',
 'film_vote_count',
 'film_mpaa_rating',
 'film_original_title',
 'film_language_name',
 'film_imdb_id',
 'film_wikidata_id',
 'film_countries',
 'film_year',
 'film_release_date',
 'film_popularity',
 'film_budget',
 'film_revenue',
 'film_studios',
 'film_director',
 'film_soundtrack_composer_raw',
 'film_top_cast',
 'film_keywords',
 'film_ingested_at',
 'release_group_id',
 'release_group_mbid',
 'release_id',
 'release_mbid',
 'album_title',
 'rg_primary_type',
 'rg_secondary_types',
 'match_method',
 'album_soundtrack_type',
 'album_notes',
 'album_matched_at',
 'album_us_release_date',
 'album_us_release_year',
 'album_us_release_month_min_observed',
 'album_us_release_day_min_observed',
 'us_date_has_missing_month',
 'us_date_has_missing_day',
 'us_any_event_missing_month',
 'us_any_event_missing_day',
 'release_title',
 'release_status',
 'release_packaging',
 'barcode',
 'release_language',
 'release_script',
 'release_comment',
 'rg_tags_text',
 'release_tags_text',
 'label_names',
 'label_mbids',
 'label_tags_text',
 'rg_rating',
 'rg_rating_count',
 'release_meta_date_added',
 'release_meta_info_url',
 'release_meta_amazon_asin',
 'release_meta_cover_art_presence',
 'album_artist_ids_text',
 'album_artist_names_text',
 'album_artist_mbids_text',
 'album_artist_types_text',
 'album_artist_max_film_ct_in_spine',
 'album_artist_max_soundtrack_rg_ct_in_spine',
 'medium_id',
 'disc_number',
 'medium_format',
 'track_id',
 'track_number',
 'track_title',
 'track_length_ms',
 'recording_id',
 'recording_mbid',
 'recording_title',
 'recording_length_ms',
 'recording_artist_credit',
 'isrcs_text',
 'recording_first_release_year',
 'recording_first_release_month',
 'recording_first_release_day',
 'recording_tags_text',
 'work_ids_text',
 'work_titles_text',
 'composer_names_text',
 'lyricist_names_text',
 'is_canonical_soundtrack',
 'is_canonical_songtrack',
 'canonical_rule',
 'canonical_songtrack_rule',
 'days_since_film_release',
 'days_since_album_release',
 'album_ambient_experimental',
 'album_classical_orchestral',
 'album_electronic',
 'album_hip_hop_rnb',
 'album_pop',
 'album_rock',
 'album_world_folk',
 'primary_artist_id',
 'primary_artist',
 'album_primary_artist_id',
 'Artist_media_composer_orchestral',
 'Artist_pop_vocalist',
 'Artist_rock_artist_band',
 'Artist_electronic_producer',
 'Artist_jazz_traditional',
 'Artist_world_folk_regional',
 'film_is_action',
 'film_is_adventure',
 'film_is_animation',
 'film_is_comedy',
 'film_is_crime',
 'film_is_documentary',
 'film_is_drama',
 'film_is_family',
 'film_is_fantasy',
 'film_is_history',
 'film_is_horror',
 'film_is_music',
 'film_is_mystery',
 'film_is_romance',
 'film_is_science_fiction',
 'film_is_tv_movie',
 'film_is_thriller',
 'film_is_war',
 'film_is_western',
 'vote_count_above_500',
 'composer_primary_clean',
 'track_title_cleaned',
 'spotify_track_id',
 'spotify_url',
 'spotify_popularity',
 'key',
 'mode',
 'camelot',
 'tempo',
 'duration',
 'popularity',
 'energy',
 'danceability',
 'happiness',
 'acousticness',
 'instrumentalness',
 'liveness',
 'speechiness',
 'loudness']

In [33]:
df_wide.sample(10)

,tmdb_id,film_title,film_adult,film_runtime_min,film_genres,film_rating,film_vote_count,film_mpaa_rating,film_original_title,film_language_name,...,duration,popularity,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness
63265,1077295,Godspeed,False,100,Comedy,5.200,24,NR,人生路不熟,Mandarin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55322,992190,Box,False,9,Horror,4.500,51,NR,Box,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14717,213681,Masterminds,False,95,"Action, Comedy, Crime",5.800,1816,PG-13,Masterminds,English,...,3:54,36.0,97.0,44.0,70.0,0.0,1.0,14.0,10.0,-5 dB
62732,472221,The Goat Life,False,173,"Drama, Adventure",7.233,58,NR,ആടുജീവിതം,Malayalam,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49906,619730,Don't Worry Darling,False,123,"Science Fiction, Mystery, Thriller",6.770,2827,R,Don't Worry Darling,English,...,1:22,11.0,1.0,38.0,4.0,99.0,86.0,8.0,3.0,-32 dB
74746,1175942,The Bad Guys 2,False,104,"Family, Comedy, Crime, Adventure, Animation",7.711,622,PG,The Bad Guys 2,English,...,2:36,22.0,63.0,55.0,18.0,1.0,89.0,9.0,4.0,-13 dB
21210,463272,Johnny English Strikes Again,False,88,"Action, Adventure, Comedy",6.267,2666,PG,Johnny English Strikes Again,English,...,3:53,4.0,43.0,27.0,10.0,65.0,90.0,23.0,4.0,-13 dB
52998,705996,Decision to Leave,False,139,"Thriller, Mystery, Romance",7.324,1413,NR,헤어질 결심,Korean,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64773,533535,Deadpool & Wolverine,False,128,"Action, Comedy, Science Fiction",7.564,8165,R,Deadpool & Wolverine,English,...,2:55,65.0,88.0,72.0,4.0,4.0,1.0,13.0,5.0,-6 dB
38254,329013,III,False,80,"Thriller, Drama, Horror",4.664,61,NR,III,Russian,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
# Sanity check - check for number of rows with value for key

count_with_key = (
    df_wide["key"].notna()
    & (df_wide["key"].str.strip() != "")
).sum()

count_with_key

32428

In [35]:
# Sanity check - check for number of rows with value for duration

count_with_duration = (
    df_wide["duration"].notna()
    & (df_wide["duration"].str.strip() != "")
).sum()

count_with_duration

32428

In [36]:
# Sanity check - check for number of rows with value for danceability

count_with_danceability = df_wide["danceability"].notna().sum()
count_with_danceability

32428

In [37]:
# Sanity check - check for number of rows with value for tempo

count_with_tempo = df_wide["tempo"].notna().sum()
count_with_tempo

32428

In [38]:
# Save wide file to CSV

out_path = "/work/pipeline/4.4.Wide_rapid_api_pull.csv"

df_wide.to_csv(out_path, index=False)

In [39]:
# Check track file

filepath = '/work/pipeline/4.3.Tracks_spotify_ids.csv'
df_track = pd.read_csv(filepath)

print(f"Number of records in track file before merge: {len(df_track)}")
df_track.head()

Number of records in track file before merge: 78992

,tmdb_id,film_title,release_group_id,release_id,match_method,album_us_release_date,us_date_has_missing_month,us_date_has_missing_day,medium_id,disc_number,...,isrcs_text,recording_tags_text,work_ids_text,work_titles_text,composer_names_text,lyricist_names_text,track_title_cleaned,spotify_track_id,spotify_url,spotify_popularity
0,158852,Tomorrowland,1527294,1608979,imdb_exact,2015-06-09,False,False,1692109,1,...,USWD11570549,NaN,14179222,Frank Frank,Michael Giacchino,NaN,Frank Frank,1xHD9H5zKIZZnrYVhI013z,https://open.spotify.com/track/1xHD9H5zKIZZnrY...,3.0
1,545836,Amundsen,2122978,2367092,imdb_exact,NaN,NaN,NaN,2563555,1,...,NaN,NaN,NaN,NaN,NaN,NaN,Planning the Expedition,7qQ03CeoqvvOQN5KO2jOrx,https://open.spotify.com/track/7qQ03CeoqvvOQN5...,3.0
2,524434,Eternals,2804779,3233921,imdb_exact,NaN,NaN,NaN,3523483,1,...,USHR12142555,NaN,14265689,Somewhere in Time,Ramin Djawadi,NaN,Somewhere in Time,1hXr4J2zeXIEpuYhds0o7L,https://open.spotify.com/track/1hXr4J2zeXIEpuY...,14.0
3,291851,Field of Lost Shoes,1414263,1474985,imdb_exact,2014-09-09,False,False,1540034,1,...,NaN,NaN,14876001,The Language of the Winners,Frederik Wiedmann,NaN,The Language of the Winners,NaN,NaN,NaN
4,419916,Funny Cow,1976129,2181386,title_contains_strict,NaN,NaN,NaN,2352738,1,...,UKPDC1800007,NaN,NaN,NaN,NaN,NaN,Leaving Mikes House,2N03m8NTjSQEUe4LpTT0C9,https://open.spotify.com/track/2N03m8NTjSQEUe4...,1.0

In [40]:
list(df_track.columns)

['tmdb_id',
 'film_title',
 'release_group_id',
 'release_id',
 'match_method',
 'album_us_release_date',
 'us_date_has_missing_month',
 'us_date_has_missing_day',
 'medium_id',
 'disc_number',
 'medium_format',
 'track_id',
 'track_number',
 'track_title',
 'track_length_ms',
 'recording_id',
 'recording_mbid',
 'recording_title',
 'recording_length_ms',
 'recording_artist_credit',
 'recording_first_release_year',
 'recording_first_release_month',
 'recording_first_release_day',
 'isrcs_text',
 'recording_tags_text',
 'work_ids_text',
 'work_titles_text',
 'composer_names_text',
 'lyricist_names_text',
 'track_title_cleaned',
 'spotify_track_id',
 'spotify_url',
 'spotify_popularity']

In [41]:
# Check for duplicate keys before merging

assert not final_schema_deduped_df.duplicated(
    subset=[
        "spotify_track_id",
        "recording_artist_credit",
        "track_title_cleaned",
    ]
).any(), "Duplicate composite keys in final_schema_deduped_df"

In [42]:
# Merge audio features into track file

cols_to_add = [
    "spotify_track_id",
    "recording_artist_credit",
    "track_title_cleaned",
    "key",
    "mode",
    "camelot",
    "tempo",
    "duration",
    "popularity",
    "energy",
    "danceability",
    "happiness",
    "acousticness",
    "instrumentalness",
    "liveness",
    "speechiness",
    "loudness",
]

df_track = df_track.merge(
    final_schema_deduped_df[cols_to_add],
    on=[
        "spotify_track_id",
        "recording_artist_credit",
        "track_title_cleaned",
    ],
    how="left"
)

print(f"Number of records after merging: {len(df_track)}")
df_track.head()

Number of records after merging: 78992

,tmdb_id,film_title,release_group_id,release_id,match_method,album_us_release_date,us_date_has_missing_month,us_date_has_missing_day,medium_id,disc_number,...,duration,popularity,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness
0,158852,Tomorrowland,1527294,1608979,imdb_exact,2015-06-09,False,False,1692109,1,...,2:23,41.0,55.0,84.0,63.0,7.0,0.0,17.0,30.0,-9 dB
1,545836,Amundsen,2122978,2367092,imdb_exact,NaN,NaN,NaN,2563555,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,524434,Eternals,2804779,3233921,imdb_exact,NaN,NaN,NaN,3523483,1,...,4:59,63.0,99.0,31.0,4.0,0.0,9.0,10.0,32.0,-4 dB
3,291851,Field of Lost Shoes,1414263,1474985,imdb_exact,2014-09-09,False,False,1540034,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,419916,Funny Cow,1976129,2181386,title_contains_strict,NaN,NaN,NaN,2352738,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
# Sanity check - check for number of rows with value for key

count_with_key = (
    df_track["key"].notna()
    & (df_track["key"].str.strip() != "")
).sum()

count_with_key

32424

In [44]:
# Sanity check - check for number of rows with value for danceability

count_with_danceability = df_track["danceability"].notna().sum()
count_with_danceability

32424

In [45]:
# Save track file to CSV

out_path = "/work/pipeline/4.4.Tracks_rapid_api_pull.csv"

df_track.to_csv(out_path, index=False)

In [46]:
# Albums and Artists carry over

import shutil

shutil.copy(
    "./pipeline/4.3.Albums_spotify_ids.csv",
    "./pipeline/4.4.Albums_rapid_api_pull.csv"
)

shutil.copy(
    "./pipeline/4.3.Artists_spotify_ids.csv",
    "./pipeline/4.4.Artists_rapid_api_pull.csv"
)

'./pipeline/4.4.Artists_rapid_api_pull.csv'

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=b124131d-2024-4253-bb46-8043aed4b78f' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>