# I\. Setup and Inspection

In [1]:
# Standard library imports
import os
from typing import List, Union

# Third-party imports
import numpy as np
import pandas as pd

In [2]:
# Load the dataframes
tracks_df = pd.read_csv("/work/pipeline/4.7.Tracks_analytics_set.csv")
wide_df = pd.read_csv("/work/pipeline/4.7.Wide_analytics_set.csv")

/tmp/ipykernel_602/2597499938.py:3: DtypeWarning: Columns (58,84) have mixed types. Specify dtype option on import or set low_memory=False.
  wide_df = pd.read_csv("/work/pipeline/4.7.Wide_analytics_set.csv")

In [3]:
print(f"Total records in tracks_df: {tracks_df.shape[0]}")
print(tracks_df.columns)
tracks_df.head()

Total records in tracks_df: 32261
Index(['tmdb_id', 'film_title', 'release_group_id', 'release_id',
       'match_method', 'album_us_release_date', 'us_date_has_missing_month',
       'us_date_has_missing_day', 'medium_id', 'disc_number', 'medium_format',
       'track_id', 'track_number', 'track_title', 'track_length_ms',
       'recording_id', 'recording_mbid', 'recording_title',
       'recording_length_ms', 'recording_artist_credit',
       'recording_first_release_year', 'recording_first_release_month',
       'recording_first_release_day', 'isrcs_text', 'recording_tags_text',
       'work_ids_text', 'work_titles_text', 'composer_names_text',
       'lyricist_names_text', 'award_year', 'oscar_score_nominee',
       'oscar_score_winner', 'oscar_song_nominee', 'oscar_song_winner',
       'globes_score_nominee', 'globes_score_winner', 'globes_song_nominee',
       'globes_song_winner', 'critics_score_nominee', 'critics_score_winner',
       'critics_song_nominee', 'critics_song_winner', 'bafta_score_nominee',
       'bafta_score_winner', 'lfm_track_status', 'lfm_track_listeners',
       'lfm_track_playcount', 'lfm_track_url', 'lfm_track_query_method',
       'lfm_track_pulled_at', 'track_title_cleaned', 'spotify_track_id',
       'spotify_url', 'spotify_popularity', 'key', 'mode', 'camelot', 'tempo',
       'duration', 'popularity', 'energy', 'danceability', 'happiness',
       'acousticness', 'instrumentalness', 'liveness', 'speechiness',
       'loudness', 'log_lfm_track_playcount'],
      dtype='object')

,tmdb_id,film_title,release_group_id,release_id,match_method,album_us_release_date,us_date_has_missing_month,us_date_has_missing_day,medium_id,disc_number,...,popularity,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness,log_lfm_track_playcount
0,158852,Tomorrowland,1527294,1608979,imdb_exact,2015-06-09,False,False,1692109,1,...,41.0,55.0,84.0,63.0,7.0,0.0,17.0,30.0,-9 dB,7.229839
1,524434,Eternals,2804779,3233921,imdb_exact,NaN,NaN,NaN,3523483,1,...,63.0,99.0,31.0,4.0,0.0,9.0,10.0,32.0,-4 dB,8.994545
2,302946,The Accountant,1765530,1914190,title_contains_strict,2016-10-01,False,False,2044240,1,...,15.0,9.0,24.0,8.0,99.0,91.0,14.0,4.0,-26 dB,8.100161
3,382614,The Book of Henry,1826846,1992770,imdb_exact,2017-06-16,False,False,2134766,1,...,2.0,0.0,18.0,6.0,99.0,97.0,13.0,5.0,-38 dB,6.626718
4,507086,Jurassic World Dominion,2995405,3480541,imdb_exact,2022-06-07,False,False,3792093,1,...,13.0,29.0,36.0,3.0,14.0,92.0,7.0,5.0,-16 dB,4.382027

# II\. Check for Duplicate Spotify Track ID's

During the merging of the API dumps from the Spotify and Soundnet APIs, we noticed that there were some instances where Spotify Tack ID's were showing up more than once, sometimes with records that had different track titles\. Below, we set out to investigate this further\.

In [4]:
# Check for duplicates in spotify_track_id

duplicate_row_count = tracks_df["spotify_track_id"].duplicated(keep=False).sum()
duplicate_row_count

3131

In [5]:
# Inspect the rows

duplicate_rows_df = (
    tracks_df
    .loc[tracks_df["spotify_track_id"].duplicated(keep=False)]
    .sort_values("spotify_track_id")
)

duplicate_rows_df

,tmdb_id,film_title,release_group_id,release_id,match_method,album_us_release_date,us_date_has_missing_month,us_date_has_missing_day,medium_id,disc_number,...,popularity,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness,log_lfm_track_playcount
13533,256962,Little Boy,1881800,2062060,title_contains_strict,NaN,NaN,NaN,2215964,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.308268
12743,256962,Little Boy,1881800,2062060,title_contains_strict,NaN,NaN,NaN,2215964,1,...,1.0,7.0,41.0,4.0,98.0,90.0,11.0,3.0,-20 dB,4.343805
4093,681887,Cosmic Sin,2651773,3038673,title_contains_strict,NaN,NaN,NaN,3307310,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.386294
7630,681887,Cosmic Sin,2651773,3038673,title_contains_strict,NaN,NaN,NaN,3307310,1,...,33.0,33.0,71.0,15.0,21.0,82.0,8.0,3.0,-14 dB,1.609438
19601,181283,Child 44,1788849,1943756,imdb_exact,2015-04-14,False,False,2078935,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.543295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32207,238615,Self/less,1578295,1673964,imdb_exact,2015-07-24,False,False,1767566,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
32219,614560,Mank,2540393,2901614,imdb_exact,2021-01-01,True,True,3156425,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.574711
32243,515195,Yesterday,2188399,2449174,imdb_exact,2019-06-21,False,False,2652336,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.806662
32254,374205,One Piece Film: GOLD,1686511,1811018,title_contains_strict,NaN,NaN,NaN,1925163,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.098612
32260,402431,Wicked,3945984,4694268,imdb_exact,2024-12-02,False,False,5107987,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.945910

As track\_id is a unique identifier in the source data that preceded the Spotify API pulls, we wanted to do a closer inspection of records where spotify\_track\_id's were assigned to different track\_id's\.

In [6]:
# ------------------------------------------------------------
# STEP 1: Identify Spotify IDs that map to multiple track_ids
# ------------------------------------------------------------

spotify_id_multi_track = (
    tracks_df
    # Group rows by spotify_track_id
    .groupby("spotify_track_id")["track_id"]
    
    # Count the number of DISTINCT track_id values per spotify ID
    # (nunique = number of unique values)
    .nunique()
    
    # Convert the resulting Series back into a dataframe
    .reset_index(name="distinct_track_ids")
    
    # Keep only Spotify IDs that map to MORE THAN ONE track_id
    # These represent potential ID collisions
    .query("distinct_track_ids > 1")
)


# ------------------------------------------------------------
# STEP 2: Flag all rows involved in those collisions
# ------------------------------------------------------------

tracks_df["spotify_track_id_collision"] = (
    tracks_df["spotify_track_id"]
    
    # Check whether each row's spotify_track_id
    # appears in the list of problematic IDs
    .isin(spotify_id_multi_track["spotify_track_id"])
)

# This creates a new Boolean column:
#   True  = this row is part of a Spotify ID collision
#   False = this row is not part of a collision


# ------------------------------------------------------------
# STEP 3: Extract only the rows involved in collisions
# ------------------------------------------------------------

collision_rows_df = (
    tracks_df
    
    # Keep only rows where collision flag is True
    .loc[tracks_df["spotify_track_id_collision"]]
    
    # Sort for readability:
    # First by spotify ID, then by track_id
    .sort_values(["spotify_track_id", "track_id"])
)

collision_rows_df

,tmdb_id,film_title,release_group_id,release_id,match_method,album_us_release_date,us_date_has_missing_month,us_date_has_missing_day,medium_id,disc_number,...,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness,log_lfm_track_playcount,spotify_track_id_collision
13533,256962,Little Boy,1881800,2062060,title_contains_strict,NaN,NaN,NaN,2215964,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.308268,True
12743,256962,Little Boy,1881800,2062060,title_contains_strict,NaN,NaN,NaN,2215964,1,...,7.0,41.0,4.0,98.0,90.0,11.0,3.0,-20 dB,4.343805,True
4093,681887,Cosmic Sin,2651773,3038673,title_contains_strict,NaN,NaN,NaN,3307310,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.386294,True
7630,681887,Cosmic Sin,2651773,3038673,title_contains_strict,NaN,NaN,NaN,3307310,1,...,33.0,71.0,15.0,21.0,82.0,8.0,3.0,-14 dB,1.609438,True
19601,181283,Child 44,1788849,1943756,imdb_exact,2015-04-14,False,False,2078935,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.543295,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20120,421658,Final Score,2994950,3479988,imdb_exact,NaN,NaN,NaN,3791525,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.730100,True
29060,403300,A Hidden Life,2276906,2563867,title_contains_strict,NaN,NaN,NaN,2781258,1,...,33.0,16.0,6.0,26.0,88.0,12.0,4.0,-12 dB,10.145374,True
20828,527774,Raya and the Last Dragon,2616741,3084171,title_contains_strict,2021-02-26,False,False,3357259,1,...,33.0,16.0,6.0,26.0,88.0,12.0,4.0,-12 dB,0.693147,True
29269,458253,Missing Link,2146100,2395350,imdb_exact,2019-06-14,False,False,2594747,1,...,11.0,24.0,5.0,41.0,85.0,11.0,4.0,-14 dB,7.423568,True
26563,605886,To Catch a Killer,3345882,3931521,imdb_exact,NaN,NaN,NaN,4282415,1,...,11.0,24.0,5.0,41.0,85.0,11.0,4.0,-14 dB,1.609438,True

Here we noticed that there were some instances where the same spotify\_track\_id was being returned for two tracks with similar, but not identical titles \(e\.g\., Space Gate, Assault at the Space Gate\)\. Fortunately, when we got the results from the Spotify API, we stored the track titles that Spotify was attempting to match to\. We will merge those in from the API result CSVs in order to compare those\.

# III\. Compare Mis\-matched Track Titles

In [7]:
# Load CSV from first Spotify API run

filepath_first_run = '/work/api_dumps/pycharm_spotify_id_lookup_results.csv'
df_first_run = pd.read_csv(filepath_first_run)

print(f"Total records in 1st API run: {df_first_run.shape[0]}")
df_first_run.head()

Total records in 1st API run: 47500

,recording_artist_credit,track_title_cleaned,spotify_track_id,spotify_url,matched_track_name,matched_artists,matched_album,matched_release_date,matched_popularity,query_used,lookup_error,attempts_used
0,Philippe Vachey,Alone in the Dark Theme,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,Philippe Vachey,[data track],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,Mr. Brady,Disqusting,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,Rob the Viking,Move It Up,21h0xKdO8E7EY0H90fApYB,https://open.spotify.com/track/21h0xKdO8E7EY0H...,Move It Up,Rob The Viking,Beats to Pillage and Conquer By,1/1/2003,1.0,"track:""Move It Up"" artist:""Rob the Viking""",NaN,1
4,Son Doobie,Party People,1ZvGInqvCALu6OxcGR4G5H,https://open.spotify.com/track/1ZvGInqvCALu6Ox...,Party People,Son Doobie,Funk Superhero,5/20/2003,6.0,"track:""Party People"" artist:""Son Doobie""",NaN,1

In [8]:
# Load CSV from the second Spotify API run

filepath_second_run = '/work/api_dumps/scoped_spotify_id_lookup_results.csv'
df_spotify_second_run = pd.read_csv(filepath_second_run)

print(f"Number of records: {len(df_spotify_second_run)}")
df_spotify_second_run.head()

Number of records: 15838

,sp_tracking_id,recording_artist_credit,track_title_cleaned,spotify_track_id,spotify_url,matched_track_name,matched_artists,matched_album,matched_release_date,matched_popularity,query_used,lookup_error,attempts_used
0,3,Neil Sedaka,Calendar Girl (1999 remastered version),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,127,Tom Holkenborg aka Junkie XL,Storm Is Coming (extended version),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,128,Tom Holkenborg aka Junkie XL & Christian Vorlä...,Claw Trucks (extended version),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,129,Tom Holkenborg aka Junkie XL,The Rig (extended version),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,130,Tom Holkenborg aka Junkie XL,Brothers in Arms (extended version),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [9]:
# Helper function to concatenate two dataframes and return the unique rows
# based on a specified column

def combine_unique_rows(
    df_left: pd.DataFrame,
    df_right: pd.DataFrame,
    unique_col: str,
    columns_to_keep: List[str],
) -> pd.DataFrame:
    """
    Combine two DataFrames and return a DataFrame containing only unique rows
    based on a specified column.

    Rows where `unique_col` is NaN are dropped before de-duplication.
    Missing columns in either input DataFrame are created and filled with NaN.
    """

    # ------------------------------------------------------------
    # STEP 1: Validate inputs
    # ------------------------------------------------------------

    # Ensure that the column used to determine uniqueness
    # is actually included in the output columns.
    # Without it, we could not properly de-duplicate.
    if unique_col not in columns_to_keep:
        raise ValueError(
            f"`unique_col` ('{unique_col}') must be included in columns_to_keep."
        )

    # ------------------------------------------------------------
    # STEP 2: Concatenate the two input DataFrames
    # ------------------------------------------------------------

    # Stack the two DataFrames vertically (row-wise).
    # ignore_index=True resets the row index so it runs 0...N-1
    combined_df = pd.concat([df_left, df_right], ignore_index=True)

    # ------------------------------------------------------------
    # STEP 3: Ensure all requested output columns exist
    # ------------------------------------------------------------

    # If a column listed in `columns_to_keep` does not exist
    # in either df_left or df_right, create it and fill with NaN.
    # This guarantees a consistent schema in the final output.
    for col in columns_to_keep:
        if col not in combined_df.columns:
            combined_df[col] = pd.NA

    # ------------------------------------------------------------
    # STEP 4: Clean and de-duplicate
    # ------------------------------------------------------------

    combined_unique_df = (
        combined_df

        # Drop rows where the uniqueness column is missing.
        # We cannot determine uniqueness if the key is NaN.
        .dropna(subset=[unique_col])

        # Keep only the requested columns (and enforce column order).
        .loc[:, columns_to_keep]

        # Remove duplicate rows based on `unique_col`.
        # keep="first" preserves the first occurrence encountered.
        .drop_duplicates(subset=unique_col, keep="first")

        # Reset the index for a clean, sequential index.
        .reset_index(drop=True)
    )

    # ------------------------------------------------------------
    # STEP 5: Return result
    # ------------------------------------------------------------

    return combined_unique_df

In [10]:
# Concatenate the two API result sets and de-duplicate on Spotify ID

cols_to_keep = ['spotify_track_id', 'matched_track_name', 'matched_artists', 'matched_album']

spotify_api_matches_df = combine_unique_rows(
    df_left=df_first_run,
    df_right=df_spotify_second_run,
    unique_col="spotify_track_id",
    columns_to_keep=cols_to_keep
)

print(f"Number of records in combined df: {len(spotify_api_matches_df)}")
spotify_api_matches_df.head()

Number of records in combined df: 49004

,spotify_track_id,matched_track_name,matched_artists,matched_album
0,21h0xKdO8E7EY0H90fApYB,Move It Up,Rob The Viking,Beats to Pillage and Conquer By
1,1ZvGInqvCALu6OxcGR4G5H,Party People,Son Doobie,Funk Superhero
2,2d4rwnZlHB13bnqZIwvzEg,What I Do Know,Moka Only,Martian Xmas 2007
3,5P71zuxh2774jjtNhfRBVk,Red Hook Day,Shabazz the Disciple,The Book of Shabazz (Hidden Scrollz)
4,3aepQNLmLMTKJm51jnXHSK,Revolving,Oddities,The Scenic Route

In [11]:
# Validate there are no nulls/blanks for spotify_track_id

assert (
    spotify_api_matches_df["spotify_track_id"].notna()
    & (spotify_api_matches_df["spotify_track_id"].astype(str).str.strip() != "")
).all(), "spotify_track_id contains null or blank values"

In [12]:
# Helper function to join two dataframes, with de-dupe

def join_with_dedup(
    left_df: pd.DataFrame,
    right_df: pd.DataFrame,
    on: Union[str, List[str]],
    how: str = "left",
    columns_to_add: Union[List[str], None] = None,
    suffixes: tuple = ("", "_right"),
) -> pd.DataFrame:
    """
    Join two DataFrames with de-duplication on the right DataFrame.

    Parameters
    ----------
    left_df : pd.DataFrame
        Left DataFrame.
    right_df : pd.DataFrame
        Right DataFrame (will be de-duplicated before join).
    on : str or list of str
        Column(s) to join on.
    how : str, default "left"
        Type of join: 'left', 'right', 'inner', 'outer'.
    columns_to_add : list of str or None, default None
        Columns from right_df to bring in. If None, brings all columns.
        Join keys are automatically included.
    suffixes : tuple, default ("", "_right")
        Suffixes to apply to overlapping column names.

    Returns
    -------
    pd.DataFrame
        Joined DataFrame.
    """

    # Get dataframe length before merging
    orig_count = len(left_df)

    # Normalize join keys
    on_cols = [on] if isinstance(on, str) else list(on)

    # Determine columns to keep from right_df
    if columns_to_add is None:
        right_subset = right_df.copy()
    else:
        cols = list(set(on_cols + columns_to_add))
        right_subset = right_df[cols].copy()

    # De-duplicate right dataframe on join keys
    right_deduped = (
        right_subset
        .sort_values(on_cols)   # deterministic behavior
        .drop_duplicates(subset=on_cols, keep="first")
    )

    # Perform join
    joined_df = left_df.merge(
        right_deduped,
        on=on_cols,
        how=how,
        suffixes=suffixes
    )

    print(f"Number of records before merging: {orig_count}")
    print(f"Number of records after merging: {len(joined_df)}")
    return joined_df

In [13]:
# Merge the Spotify API track, artist and album name matches into the tracks dataframe

cols = ['matched_track_name', 'matched_artists', 'matched_album']

tracks_spotify_api_matches_df = join_with_dedup(
    left_df=tracks_df,
    right_df=spotify_api_matches_df,
    on=["spotify_track_id"],
    how="left",
    columns_to_add=cols
)

tracks_spotify_api_matches_df.head()

Number of records before merging: 32261
Number of records after merging: 32261

,tmdb_id,film_title,release_group_id,release_id,match_method,album_us_release_date,us_date_has_missing_month,us_date_has_missing_day,medium_id,disc_number,...,acousticness,instrumentalness,liveness,speechiness,loudness,log_lfm_track_playcount,spotify_track_id_collision,matched_album,matched_track_name,matched_artists
0,158852,Tomorrowland,1527294,1608979,imdb_exact,2015-06-09,False,False,1692109,1,...,7.0,0.0,17.0,30.0,-9 dB,7.229839,False,Tomorrowland (Original Motion Picture Soundtrack),Frank Frank,Michael Giacchino
1,524434,Eternals,2804779,3233921,imdb_exact,NaN,NaN,NaN,3523483,1,...,0.0,9.0,10.0,32.0,-4 dB,8.994545,False,Eternals (Original Motion Picture Soundtrack),Somewhere in Time,Ramin Djawadi
2,302946,The Accountant,1765530,1914190,title_contains_strict,2016-10-01,False,False,2044240,1,...,99.0,91.0,14.0,4.0,-26 dB,8.100161,False,The Accountant (Original Motion Picture Soundt...,Harbor Neuroscience,Mark Isham
3,382614,The Book of Henry,1826846,1992770,imdb_exact,2017-06-16,False,False,2134766,1,...,99.0,97.0,13.0,5.0,-38 dB,6.626718,False,The Book of Henry (Original Motion Picture Sou...,A Tender House Call,Michael Giacchino
4,507086,Jurassic World Dominion,2995405,3480541,imdb_exact,2022-06-07,False,False,3792093,1,...,14.0,92.0,7.0,5.0,-16 dB,4.382027,False,Jurassic World Dominion (Original Motion Pictu...,"She Shoots, She Scorches",Michael Giacchino

In [14]:
# Check that dataframe lengths match

assert len(tracks_df) == len(tracks_spotify_api_matches_df)

We created the function below to normalize track titles for comparison\. For example, we noticed some track titles across columns were the same except for "\(Album Mix\)\."

In [15]:
# Helper function to normalize track titles for better comparison

def normalize_title(s):
    """
    Normalize track titles for comparison by:
    - converting to string
    - trimming whitespace
    - lowercasing
    - collapsing repeated whitespace
    - removing dash-based subtitles (both standalone and in parentheses)
    - removing any 'from ...' clause following (, -, –, or —
    - removing all punctuation
    """

    return (
        s.astype(str)
         # basic normalization
         .str.strip()
         .str.lower()
         .str.replace(r"\s+", " ", regex=True)

         # remove parenthetical content ONLY if it contains a dash-subtitle keyword
         # e.g. "(Live)", "(Remastered 2011)", "(Album Mix)"
         .str.replace(
             r"\s*\(\s*(live|remaster(ed)?|album mix|single version)[^)]*\)",
             "",
             regex=True,
         )

         # remove dash-based subtitles outside parentheses
         .str.replace(
             r"\s*[-–—]\s*(live|remaster(ed)?|album mix|single version).*",
             "",
             regex=True,
         )

         # remove "from ..." clauses following (, -, –, —
         .str.replace(
             r"\s*[\(\-–—]\s*from\s+.*$",
             "",
             regex=True,
         )

         # remove all punctuation
         .str.replace(r"[^\w\s]", "", regex=True)

         # final cleanup
         .str.replace(r"\s+", " ", regex=True)
         .str.strip()
    )

In [16]:
# Identify duplicate Spotify ID's

duplicated_spotify_ids = (
    tracks_spotify_api_matches_df["spotify_track_id"]
    .value_counts()
    .loc[lambda x: x > 1]
    .index
)

In [17]:
# Inspect rows where the normalized titles do not match

problem_rows_df = (
    tracks_spotify_api_matches_df
    .loc[
        tracks_spotify_api_matches_df["spotify_track_id"].isin(duplicated_spotify_ids)
        & (
            normalize_title(tracks_spotify_api_matches_df["track_title_cleaned"])
            != normalize_title(tracks_spotify_api_matches_df["matched_track_name"])
        )
    ]
    .sort_values(["spotify_track_id", "track_title_cleaned"])
)

cols_to_view = [
    "track_id",
    "spotify_track_id",
    "track_title_cleaned",
    "matched_track_name",
    "recording_artist_credit",
    "film_title"
]

problem_rows_df[cols_to_view]

,track_id,spotify_track_id,track_title_cleaned,matched_track_name,recording_artist_credit,film_title
13533,24132403,00J2CxM1KTqSpvSiHaaZMV,Opening,Original Opening,Stephan Altman & Mark Foster,Little Boy
4093,34686884,02ViwSffy8mllqGBxSVxxz,Space Gate,Assault At The Space Gate,Scott Glasgow,Cosmic Sin
19113,22745323,03m2vvpQnPfScSx7ZRpIX1,Witness,There Is a Witness,Jon Ekstrand,Child 44
12342,34690438,03qMqIpTGo8NZy3lj5XqBH,Main Title,Voyage to the Bottom of the C (Main Title),Marco Beltrami & Brandon Roberts,Chaos Walking
16261,18690655,04CdyynOK4ZBnFWVXJXPB2,Prologue,Prologue Antiphony,Tom Holkenborg (Junkie XL),Run All Night
...,...,...,...,...,...,...
21647,35509281,7rTPLQt7vgWmexf1Axop4L,Brother,The Super Mario Brothers,Brian Tyler,F9
31709,40520278,7sBgLFmhCzl70WeoKWL2ws,I'm With You,I’m With You (A Way Out),Trent Reznor & Atticus Ross,Bones and All
18999,24972501,7t4V3WFLrO9Endw1mkbPbc,Is He Off His Meds,"Is He Off His Meds, Part B",Cliff Martinez,Den of Thieves
20120,38863952,7vS15nw4EGKDqp5v7SP1Vh,Run,A Runaway Bus,James Edward Barker & Tim Despic,Final Score
29269,27961920,7xdRysaxO6KApNwdNWaIS8,Climbing,Climbing Mountains of Trash,Carter Burwell,Missing Link

In [18]:
# Flag the false positives

false_positive_mask = (
    tracks_spotify_api_matches_df["spotify_track_id"].isin(duplicated_spotify_ids)
    & (
        normalize_title(tracks_spotify_api_matches_df["track_title_cleaned"])
        != normalize_title(tracks_spotify_api_matches_df["matched_track_name"])
    )
)

tracks_spotify_api_matches_df["spotify_api_false_positive"] = false_positive_mask
tracks_spotify_api_matches_df.head()

,tmdb_id,film_title,release_group_id,release_id,match_method,album_us_release_date,us_date_has_missing_month,us_date_has_missing_day,medium_id,disc_number,...,instrumentalness,liveness,speechiness,loudness,log_lfm_track_playcount,spotify_track_id_collision,matched_album,matched_track_name,matched_artists,spotify_api_false_positive
0,158852,Tomorrowland,1527294,1608979,imdb_exact,2015-06-09,False,False,1692109,1,...,0.0,17.0,30.0,-9 dB,7.229839,False,Tomorrowland (Original Motion Picture Soundtrack),Frank Frank,Michael Giacchino,False
1,524434,Eternals,2804779,3233921,imdb_exact,NaN,NaN,NaN,3523483,1,...,9.0,10.0,32.0,-4 dB,8.994545,False,Eternals (Original Motion Picture Soundtrack),Somewhere in Time,Ramin Djawadi,False
2,302946,The Accountant,1765530,1914190,title_contains_strict,2016-10-01,False,False,2044240,1,...,91.0,14.0,4.0,-26 dB,8.100161,False,The Accountant (Original Motion Picture Soundt...,Harbor Neuroscience,Mark Isham,False
3,382614,The Book of Henry,1826846,1992770,imdb_exact,2017-06-16,False,False,2134766,1,...,97.0,13.0,5.0,-38 dB,6.626718,False,The Book of Henry (Original Motion Picture Sou...,A Tender House Call,Michael Giacchino,False
4,507086,Jurassic World Dominion,2995405,3480541,imdb_exact,2022-06-07,False,False,3792093,1,...,92.0,7.0,5.0,-16 dB,4.382027,False,Jurassic World Dominion (Original Motion Pictu...,"She Shoots, She Scorches",Michael Giacchino,False

For the false positives, we will clear the values that the Spotify API filled so that we don't feed inaccurate data into our visuals and analysis\.

In [19]:
# Replace false positives with "NA" values

cols_to_clear = [
    "spotify_track_id",
    "spotify_url",
    "key",
    "mode",
    "camelot",
    "tempo",
    "duration",
    "popularity",
    "energy",
    "danceability",
    "happiness",
    "acousticness",
    "instrumentalness",
    "liveness",
    "speechiness",
    "loudness",
    "spotify_popularity",
]

tracks_spotify_api_matches_df.loc[
    tracks_spotify_api_matches_df["spotify_api_false_positive"],
    cols_to_clear
] = pd.NA

tracks_spotify_api_matches_df.loc[
    tracks_spotify_api_matches_df["spotify_api_false_positive"],
    cols_to_clear
].head()

,spotify_track_id,spotify_url,key,mode,camelot,tempo,duration,popularity,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness,spotify_popularity
13,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
184,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
393,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
453,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
532,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN

# V\. Merge Additional Features for Exploration

In [20]:
# Bring composer_primary_clean into our dataframe from the wide table

tracks_spotify_api_matches_df = join_with_dedup(
    left_df=tracks_spotify_api_matches_df,
    right_df=wide_df,
    on=["track_id"],
    how="left",
    columns_to_add=["composer_primary_clean"]
)

tracks_spotify_api_matches_df.head()

Number of records before merging: 32261
Number of records after merging: 32261

,tmdb_id,film_title,release_group_id,release_id,match_method,album_us_release_date,us_date_has_missing_month,us_date_has_missing_day,medium_id,disc_number,...,liveness,speechiness,loudness,log_lfm_track_playcount,spotify_track_id_collision,matched_album,matched_track_name,matched_artists,spotify_api_false_positive,composer_primary_clean
0,158852,Tomorrowland,1527294,1608979,imdb_exact,2015-06-09,False,False,1692109,1,...,17.0,30.0,-9 dB,7.229839,False,Tomorrowland (Original Motion Picture Soundtrack),Frank Frank,Michael Giacchino,False,Michael Giacchino
1,524434,Eternals,2804779,3233921,imdb_exact,NaN,NaN,NaN,3523483,1,...,10.0,32.0,-4 dB,8.994545,False,Eternals (Original Motion Picture Soundtrack),Somewhere in Time,Ramin Djawadi,False,Ramin Djawadi
2,302946,The Accountant,1765530,1914190,title_contains_strict,2016-10-01,False,False,2044240,1,...,14.0,4.0,-26 dB,8.100161,False,The Accountant (Original Motion Picture Soundt...,Harbor Neuroscience,Mark Isham,False,Mark Isham
3,382614,The Book of Henry,1826846,1992770,imdb_exact,2017-06-16,False,False,2134766,1,...,13.0,5.0,-38 dB,6.626718,False,The Book of Henry (Original Motion Picture Sou...,A Tender House Call,Michael Giacchino,False,Michael Giacchino
4,507086,Jurassic World Dominion,2995405,3480541,imdb_exact,2022-06-07,False,False,3792093,1,...,7.0,5.0,-16 dB,4.382027,False,Jurassic World Dominion (Original Motion Pictu...,"She Shoots, She Scorches",Michael Giacchino,False,Michael Giacchino

In [21]:
# Bring film genres into our dataframe from the wide table

cols_to_add = [
    'film_is_action',
    'film_is_adventure',
    'film_is_animation',
    'film_is_comedy',
    'film_is_crime',
    'film_is_documentary',
    'film_is_drama',
    'film_is_family',
    'film_is_fantasy',
    'film_is_history',
    'film_is_horror',
    'film_is_music',
    'film_is_mystery',
    'film_is_romance',
    'film_is_science_fiction',
    'film_is_tv_movie',
    'film_is_thriller',
    'film_is_war',
    'film_is_western'
    ]

tracks_spotify_api_matches_df = join_with_dedup(
    left_df=tracks_spotify_api_matches_df,
    right_df=wide_df,
    on=["tmdb_id"],
    how="left",
    columns_to_add=cols_to_add
)

tracks_spotify_api_matches_df.head()

Number of records before merging: 32261
Number of records after merging: 32261

,tmdb_id,film_title,release_group_id,release_id,match_method,album_us_release_date,us_date_has_missing_month,us_date_has_missing_day,medium_id,disc_number,...,film_is_history,film_is_music,film_is_war,film_is_crime,film_is_adventure,film_is_thriller,film_is_tv_movie,film_is_family,film_is_comedy,film_is_romance
0,158852,Tomorrowland,1527294,1608979,imdb_exact,2015-06-09,False,False,1692109,1,...,False,False,False,False,True,False,False,True,False,False
1,524434,Eternals,2804779,3233921,imdb_exact,NaN,NaN,NaN,3523483,1,...,False,False,False,False,True,False,False,False,False,False
2,302946,The Accountant,1765530,1914190,title_contains_strict,2016-10-01,False,False,2044240,1,...,False,False,False,True,False,True,False,False,False,False
3,382614,The Book of Henry,1826846,1992770,imdb_exact,2017-06-16,False,False,2134766,1,...,False,False,False,True,False,True,False,False,False,False
4,507086,Jurassic World Dominion,2995405,3480541,imdb_exact,2022-06-07,False,False,3792093,1,...,False,False,False,False,True,False,False,False,False,False

# IV\. Drop NA's and Missing Values

In [22]:
# Get info on the columns with nulls

tracks_spotify_api_matches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32261 entries, 0 to 32260
Data columns (total 94 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   tmdb_id                        32261 non-null  int64
 1   film_title                     32261 non-null  object
 2   release_group_id               32261 non-null  int64
 3   release_id                     32261 non-null  int64
 4   match_method                   32261 non-null  object
 5   album_us_release_date          15515 non-null  object
 6   us_date_has_missing_month      15515 non-null  object
 7   us_date_has_missing_day        15515 non-null  object
 8   medium_id                      32261 non-null  int64
 9   disc_number                    32261 non-null  int64
 10  medium_format                  32224 non-null  object
 11  track_id                       32261 non-null  int64
 12  track_number                   32261 non-null  int64
 13  track_title                    32261 non-null  object
 14  track_length_ms                31944 non-null  float64
 15  recording_id                   32261 non-null  int64
 16  recording_mbid                 32261 non-null  object
 17  recording_title                32261 non-null  object
 18  recording_length_ms            32015 non-null  float64
 19  recording_artist_credit        32261 non-null  object
 20  recording_first_release_year   0 non-null      float64
 21  recording_first_release_month  0 non-null      float64
 22  recording_first_release_day    0 non-null      float64
 23  isrcs_text                     18625 non-null  object
 24  recording_tags_text            1660 non-null   object
 25  work_ids_text                  13895 non-null  object
 26  work_titles_text               13895 non-null  object
 27  composer_names_text            12764 non-null  object
 28  lyricist_names_text            859 non-null    object
 29  award_year                     32261 non-null  int64
 30  oscar_score_nominee            32261 non-null  bool
 31  oscar_score_winner             32261 non-null  bool
 32  oscar_song_nominee             32261 non-null  bool
 33  oscar_song_winner              32261 non-null  bool
 34  globes_score_nominee           32261 non-null  bool
 35  globes_score_winner            32261 non-null  bool
 36  globes_song_nominee            32261 non-null  bool
 37  globes_song_winner             32261 non-null  bool
 38  critics_score_nominee          32261 non-null  bool
 39  critics_score_winner           32261 non-null  bool
 40  critics_song_nominee           32261 non-null  bool
 41  critics_song_winner            32261 non-null  bool
 42  bafta_score_nominee            32261 non-null  bool
 43  bafta_score_winner             32261 non-null  bool
 44  lfm_track_status               32261 non-null  object
 45  lfm_track_listeners            32261 non-null  float64
 46  lfm_track_playcount            32261 non-null  float64
 47  lfm_track_url                  32261 non-null  object
 48  lfm_track_query_method         32261 non-null  object
 49  lfm_track_pulled_at            32261 non-null  object
 50  track_title_cleaned            32259 non-null  object
 51  spotify_track_id               29592 non-null  object
 52  spotify_url                    29592 non-null  object
 53  spotify_popularity             29592 non-null  float64
 54  key                            28895 non-null  object
 55  mode                           28895 non-null  object
 56  camelot                        28895 non-null  object
 57  tempo                          28895 non-null  float64
 58  duration                       28895 non-null  object
 59  popularity                     28895 non-null  float64
 60  energy                         28895 non-null  float64
 61  danceability                   28895 non-null  float64
 62  happiness                      28895 non-null  float64
 63  acousticness                   28895 non-null  float64
 64  instrumentalness               28895 non-null  float64
 65  liveness                       28895 non-null  float64
 66  speechiness                    28895 non-null  float64
 67  loudness                       28895 non-null  object
 68  log_lfm_track_playcount        32261 non-null  float64
 69  spotify_track_id_collision     32261 non-null  bool
 70  matched_album                  29965 non-null  object
 71  matched_track_name             29965 non-null  object
 72  matched_artists                29965 non-null  object
 73  spotify_api_false_positive     32261 non-null  bool
 74  composer_primary_clean         32261 non-null  object
 75  film_is_drama                  32261 non-null  bool
 76  film_is_horror                 32261 non-null  bool
 77  film_is_science_fiction        32261 non-null  bool
 78  film_is_action                 32261 non-null  bool
 79  film_is_fantasy                32261 non-null  bool
 80  film_is_mystery                32261 non-null  bool
 81  film_is_western                32261 non-null  bool
 82  film_is_animation              32261 non-null  bool
 83  film_is_documentary            32261 non-null  bool
 84  film_is_history                32261 non-null  bool
 85  film_is_music                  32261 non-null  bool
 86  film_is_war                    32261 non-null  bool
 87  film_is_crime                  32261 non-null  bool
 88  film_is_adventure              32261 non-null  bool
 89  film_is_thriller               32261 non-null  bool
 90  film_is_tv_movie               32261 non-null  bool
 91  film_is_family                 32261 non-null  bool
 92  film_is_comedy                 32261 non-null  bool
 93  film_is_romance                32261 non-null  bool
dtypes: bool(35), float64(18), int64(9), object(32)
memory usage: 15.6+ MB

There are several columns in the dataframe that are either duplicative or that we don't think will be interesting for track level visuals and analysis, so these will be dropped\.

In [23]:
cols_to_drop = [
    "composer_names_text",
    "release_group_id",
    "release_id",
    "match_method",
    "album_us_release_date",
    "us_date_has_missing_month",
    "us_date_has_missing_day",
    "medium_id",
    "disc_number",
    "medium_format",
    "recording_id",
    "recording_mbid",
    "recording_title",
    "recording_length_ms",
    "recording_first_release_year",
    "recording_first_release_month",
    "recording_first_release_day",
    "isrcs_text",
    "recording_tags_text",
    "work_ids_text",
    "work_titles_text",
    "lyricist_names_text",
    "lfm_track_status",
    "lfm_track_url",
    "lfm_track_query_method",
    "lfm_track_pulled_at",
    "spotify_track_id_collision",
    "matched_artists",
    "matched_album",
    "matched_track_name",
    "spotify_api_false_positive",
    "track_length_ms",
    "popularity",
    "duration"
]

tracks_spotify_api_matches_df = tracks_spotify_api_matches_df.drop(
    columns=cols_to_drop,
    errors="ignore"  # prevents error if any column is already missing
)

In [24]:
# For track_title_cleaned NA's (there are only 2), we will just fill with the values in track_title

tracks_spotify_api_matches_df["track_title_cleaned"] = (
    tracks_spotify_api_matches_df["track_title_cleaned"]
    .fillna(tracks_spotify_api_matches_df["track_title"])
)

tracks_spotify_api_matches_df["track_title_cleaned"].isna().sum()

0

In [25]:
# Re-check for nulls with narrower column universe

tracks_spotify_api_matches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32261 entries, 0 to 32260
Data columns (total 60 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tmdb_id                  32261 non-null  int64
 1   film_title               32261 non-null  object
 2   track_id                 32261 non-null  int64
 3   track_number             32261 non-null  int64
 4   track_title              32261 non-null  object
 5   recording_artist_credit  32261 non-null  object
 6   award_year               32261 non-null  int64
 7   oscar_score_nominee      32261 non-null  bool
 8   oscar_score_winner       32261 non-null  bool
 9   oscar_song_nominee       32261 non-null  bool
 10  oscar_song_winner        32261 non-null  bool
 11  globes_score_nominee     32261 non-null  bool
 12  globes_score_winner      32261 non-null  bool
 13  globes_song_nominee      32261 non-null  bool
 14  globes_song_winner       32261 non-null  bool
 15  critics_score_nominee    32261 non-null  bool
 16  critics_score_winner     32261 non-null  bool
 17  critics_song_nominee     32261 non-null  bool
 18  critics_song_winner      32261 non-null  bool
 19  bafta_score_nominee      32261 non-null  bool
 20  bafta_score_winner       32261 non-null  bool
 21  lfm_track_listeners      32261 non-null  float64
 22  lfm_track_playcount      32261 non-null  float64
 23  track_title_cleaned      32261 non-null  object
 24  spotify_track_id         29592 non-null  object
 25  spotify_url              29592 non-null  object
 26  spotify_popularity       29592 non-null  float64
 27  key                      28895 non-null  object
 28  mode                     28895 non-null  object
 29  camelot                  28895 non-null  object
 30  tempo                    28895 non-null  float64
 31  energy                   28895 non-null  float64
 32  danceability             28895 non-null  float64
 33  happiness                28895 non-null  float64
 34  acousticness             28895 non-null  float64
 35  instrumentalness         28895 non-null  float64
 36  liveness                 28895 non-null  float64
 37  speechiness              28895 non-null  float64
 38  loudness                 28895 non-null  object
 39  log_lfm_track_playcount  32261 non-null  float64
 40  composer_primary_clean   32261 non-null  object
 41  film_is_drama            32261 non-null  bool
 42  film_is_horror           32261 non-null  bool
 43  film_is_science_fiction  32261 non-null  bool
 44  film_is_action           32261 non-null  bool
 45  film_is_fantasy          32261 non-null  bool
 46  film_is_mystery          32261 non-null  bool
 47  film_is_western          32261 non-null  bool
 48  film_is_animation        32261 non-null  bool
 49  film_is_documentary      32261 non-null  bool
 50  film_is_history          32261 non-null  bool
 51  film_is_music            32261 non-null  bool
 52  film_is_war              32261 non-null  bool
 53  film_is_crime            32261 non-null  bool
 54  film_is_adventure        32261 non-null  bool
 55  film_is_thriller         32261 non-null  bool
 56  film_is_tv_movie         32261 non-null  bool
 57  film_is_family           32261 non-null  bool
 58  film_is_comedy           32261 non-null  bool
 59  film_is_romance          32261 non-null  bool
dtypes: bool(33), float64(12), int64(4), object(11)
memory usage: 7.7+ MB

We still have a little over 3k nulls for each of our audio features, which will be the main focus of our exploration\. These would have either been due to song names that didn't hit on the Spotify API, false positives, or various API errors when querying the Soundnet API\. In the interest of preserving the variation in these columns for later analysis, we will drop the rows with null values\.

In [26]:
# Helper function to drop nulls or blanks for a specified set of columns

def drop_null_or_blank_rows(
    df: pd.DataFrame,
    cols: list | None = None
) -> pd.DataFrame:
    """
    Drop rows that contain any null or blank (empty or whitespace-only) values
    in specified columns (or all columns if none specified), and print a summary.

    Parameters
    ----------
    df : pd.DataFrame
        Input dataframe.
    cols : list, optional
        List of column names to check. If None, all columns are checked.

    Returns
    -------
    pd.DataFrame
        A new dataframe with rows containing nulls or blanks removed.
    """

    # ------------------------------------------------------------
    # 1️⃣ Determine which columns we will evaluate
    # ------------------------------------------------------------
    # If no specific columns were provided, check all columns
    if cols is None:
        cols = df.columns

    # Count rows before cleaning
    n_before = len(df)

    # Create a temporary dataframe containing only the columns
    # we want to check (this does NOT modify the original df)
    subset_df = df[cols]

    # ------------------------------------------------------------
    # 2️⃣ Build a row-level mask for null or blank values
    # ------------------------------------------------------------
    # Step A: subset_df.isna()
    #   -> True where values are actual NaN / None
    #
    # Step B: subset_df.astype(str).apply(lambda col: col.str.strip().eq(""))
    #   -> Converts values to string
    #   -> Removes leading/trailing whitespace
    #   -> Checks whether the result is an empty string ""
    #
    # Step C: Combine A and B with OR (|)
    #   -> True if value is null OR blank
    #
    # Step D: .any(axis=1)
    #   -> Collapse across columns
    #   -> True if ANY checked column in that row is null/blank
    mask_any_null_or_blank = (
        subset_df.isna()
        | subset_df.astype(str).apply(lambda col: col.str.strip().eq(""))
    ).any(axis=1)

    # Count how many rows will be dropped
    n_dropped = mask_any_null_or_blank.sum()

    # ------------------------------------------------------------
    # 3️⃣ Keep only rows that are NOT flagged
    # ------------------------------------------------------------
    # ~mask_any_null_or_blank means:
    #   Keep rows where condition is False
    df_clean = df.loc[~mask_any_null_or_blank].copy()

    # Count rows after cleaning
    n_after = len(df_clean)

    # ------------------------------------------------------------
    # 4️⃣ Print summary
    # ------------------------------------------------------------
    print(f"Columns checked: {list(cols)}")
    print(f"Input records:   {n_before}")
    print(f"Records dropped: {n_dropped}")
    print(f"Output records:  {n_after}")

    return df_clean

In [27]:
# Drop nulls for the audio feature columns

audio_cols = [
    'key',
    'mode',
    'camelot',
    'tempo',
    'energy',
    'danceability',
    'happiness',
    'acousticness',
    'instrumentalness',
    'liveness',
    'speechiness',
    'loudness'
]

tracks_clean_df = drop_null_or_blank_rows(
    tracks_spotify_api_matches_df,
    cols=audio_cols
)

tracks_clean_df.info()

Columns checked: ['key', 'mode', 'camelot', 'tempo', 'energy', 'danceability', 'happiness', 'acousticness', 'instrumentalness', 'liveness', 'speechiness', 'loudness']
Input records:   32261
Records dropped: 3366
Output records:  28895
<class 'pandas.core.frame.DataFrame'>
Index: 28895 entries, 0 to 32259
Data columns (total 60 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tmdb_id                  28895 non-null  int64
 1   film_title               28895 non-null  object
 2   track_id                 28895 non-null  int64
 3   track_number             28895 non-null  int64
 4   track_title              28895 non-null  object
 5   recording_artist_credit  28895 non-null  object
 6   award_year               28895 non-null  int64
 7   oscar_score_nominee      28895 non-null  bool
 8   oscar_score_winner       28895 non-null  bool
 9   oscar_song_nominee       28895 non-null  bool
 10  oscar_song_winner        28895 non-null  bool
 11  globes_score_nominee     28895 non-null  bool
 12  globes_score_winner      28895 non-null  bool
 13  globes_song_nominee      28895 non-null  bool
 14  globes_song_winner       28895 non-null  bool
 15  critics_score_nominee    28895 non-null  bool
 16  critics_score_winner     28895 non-null  bool
 17  critics_song_nominee     28895 non-null  bool
 18  critics_song_winner      28895 non-null  bool
 19  bafta_score_nominee      28895 non-null  bool
 20  bafta_score_winner       28895 non-null  bool
 21  lfm_track_listeners      28895 non-null  float64
 22  lfm_track_playcount      28895 non-null  float64
 23  track_title_cleaned      28895 non-null  object
 24  spotify_track_id         28895 non-null  object
 25  spotify_url              28895 non-null  object
 26  spotify_popularity       28895 non-null  float64
 27  key                      28895 non-null  object
 28  mode                     28895 non-null  object
 29  camelot                  28895 non-null  object
 30  tempo                    28895 non-null  float64
 31  energy                   28895 non-null  float64
 32  danceability             28895 non-null  float64
 33  happiness                28895 non-null  float64
 34  acousticness             28895 non-null  float64
 35  instrumentalness         28895 non-null  float64
 36  liveness                 28895 non-null  float64
 37  speechiness              28895 non-null  float64
 38  loudness                 28895 non-null  object
 39  log_lfm_track_playcount  28895 non-null  float64
 40  composer_primary_clean   28895 non-null  object
 41  film_is_drama            28895 non-null  bool
 42  film_is_horror           28895 non-null  bool
 43  film_is_science_fiction  28895 non-null  bool
 44  film_is_action           28895 non-null  bool
 45  film_is_fantasy          28895 non-null  bool
 46  film_is_mystery          28895 non-null  bool
 47  film_is_western          28895 non-null  bool
 48  film_is_animation        28895 non-null  bool
 49  film_is_documentary      28895 non-null  bool
 50  film_is_history          28895 non-null  bool
 51  film_is_music            28895 non-null  bool
 52  film_is_war              28895 non-null  bool
 53  film_is_crime            28895 non-null  bool
 54  film_is_adventure        28895 non-null  bool
 55  film_is_thriller         28895 non-null  bool
 56  film_is_tv_movie         28895 non-null  bool
 57  film_is_family           28895 non-null  bool
 58  film_is_comedy           28895 non-null  bool
 59  film_is_romance          28895 non-null  bool
dtypes: bool(33), float64(12), int64(4), object(11)
memory usage: 7.1+ MB

That appeared to have resolved any remaining nulls in the dataframe, but we noticed that loudness should be numeric, not object\.

In [28]:
# Convert loudness to numeric

tracks_clean_df["loudness"] = (
    tracks_clean_df["loudness"]
    .str.replace(" dB", "", regex=False)
    .astype(float)
)

In [29]:
print(f"Total records after cleaning: {len(tracks_clean_df)}")
tracks_clean_df[audio_cols].head()

Total records after cleaning: 28895

,key,mode,camelot,tempo,energy,danceability,happiness,acousticness,instrumentalness,liveness,speechiness,loudness
0,F,minor,4A,151.0,55.0,84.0,63.0,7.0,0.0,17.0,30.0,-9.0
1,F,minor,4A,140.0,99.0,31.0,4.0,0.0,9.0,10.0,32.0,-4.0
2,A,minor,8A,78.0,9.0,24.0,8.0,99.0,91.0,14.0,4.0,-26.0
3,C,minor,5A,61.0,0.0,18.0,6.0,99.0,97.0,13.0,5.0,-38.0
4,C#,major,3B,110.0,29.0,36.0,3.0,14.0,92.0,7.0,5.0,-16.0

# VI\. Write to File

In [30]:
# Save cleaned track file to CSV

out_path = "/work/pipeline/5.4.a.Tracks_clean.csv"

tracks_clean_df.to_csv(out_path, index=False)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=b124131d-2024-4253-bb46-8043aed4b78f' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>